### ISSUE TITLE
The process was terminated due to an unhandled exception. Exception Info: System.InvalidOperationException

### ISSUE THREAD

**Issue by sargiss** [confluentinc/confluent-kafka-dotnet#1051]
kafka client craches host service.
===========
create two singlton producers, one per different message types
all works fine, messages aea sended successfully. but in some point of time host process (windows service) get faulted and crashed with following stack:
 
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException
   at System.Collections.Hashtable+HashtableEnumerator.MoveNext()
   at System.Runtime.Remoting.Messaging.LogicalCallContext.Clone()
   at System.Threading.ExecutionContext.Capture(System.Threading.StackCrawlMark ByRef, CaptureOptions)
   at System.Threading.ExecutionContext.FastCapture()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.GetCompletionAction(System.Threading.Tasks.Task, MoveNextRunner ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].AwaitUnsafeOnCompleted[[System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[Confluent.Kafka.Producer`2+<ProduceAsync>d__51[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], Confluent.Kafka, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null]](ConfiguredTaskAwaiter<System.__Canon> ByRef, <ProduceAsync>d__51<System.__Canon,System.__Canon> ByRef)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch() 

Here is how we create and consume publisher (as it was forementioned KafkaJsonPublisher create as singleton object):

public class KafkaJsonPublisher: IDisposable
    {
        Lazy<IProducer<Null, string>> _producer;
        Lazy<IProducer<string, string>> _producerKeyed;

        public KafkaJsonPublisher(IKafkaBusSettings kafkaBusSettings)
        {
            var conf = new ProducerConfig { BootstrapServers = kafkaBusSettings.BootstrapServer };
            if (kafkaBusSettings.MessageTimeoutSec.HasValue)
                conf.MessageTimeoutMs = kafkaBusSettings.MessageTimeoutSec.Value * 1000;

            _producer = new Lazy<IProducer<Null, string>>(() => new ProducerBuilder<Null, string>(conf).Build());
            _producerKeyed = new Lazy<IProducer<string, string>>(() => new ProducerBuilder<string, string>(conf).Build());

        }

        public void Publish(KafkaDataEvent retailEvent)
        {
            if (string.IsNullOrEmpty(retailEvent.Key))
            {
                PublishInternal(_producer, retailEvent.Topic, new Message<Null, string> { Value = retailEvent.Data });
            }
            else
            {
                PublishInternal(_producerKeyed, retailEvent.Topic, new Message<string, string> { Key = retailEvent.Key, Value = retailEvent.Data });
            }
        }

        private void PublishInternal<TKey>(Lazy<IProducer<TKey, string>> producer, string topic, Message<TKey, string> msg)
        {
                producer.Value.ProduceAsync(topic, msg).ContinueWith(t => {
                    if (!t.IsFaulted)
                    {
                        if (t.Result.Status != PersistenceStatus.Persisted){
                            //some logging
                        }
                    }
                });
        }
    }

**Comment by prashah-confluent** [comment]
Thanks for reporting this issue.

The version mentioned here is no longer supported. If you are still encountering this problem with a newer, supported version of the library, please feel free to open a new issue with updated details, and we’ll be happy to take a closer look.

Thanks!
