### ISSUE TITLE
Unable to handle KafkaException on commit

### ISSUE THREAD

**Issue by mikenorgate** [confluentinc/confluent-kafka-dotnet#1054]
Description
===========
I'm experiencing an issue where manually committing is throwing an exception (due to rebalance in progress) however I am unable to handle this exception which is causing the host application to crash

Confluent.Kafka Version: 1.0.1.1
Kafka Version: confluentinc/cp-kafka:5.0.1 docker image

How to reproduce
================

This is the code that I have for doing the commit

```
void CommitTimerCallback(object state)
{
    try
    {
        IDictionary<IConsumer<TKey, TValue>, List<TopicPartitionOffset>> outstandingCommits = _outstandingCommits;

        foreach (var consumerOffsets in outstandingCommits)
               consumerOffsets.Key.Commit(consumerOffsets.Value);
    }
    catch (Exception ex)
    {
        _logger.Error(ex, "Error while committing kafka offsets");
    }
}
```

I'm able to catch the exception by using the `UnhadledException` event as follows

```
AppDomain.CurrentDomain.UnhandledException += (sender, eventArgs) =>
 {
    //log exception
};
```

and I get the this stack trace

```
Confluent.Kafka.KafkaException: Broker: Group rebalance in progress
at Confluent.Kafka.Impl.SafeKafkaHandle.Commit(IEnumerable`1 offsets)
at Confluent.Kafka.Consumer`2.Commit(IEnumerable`1 offsets)
at Polystream.Teleminion.Plugins.Kafka.KafkaConsumer`2.CommitTimerCallback(Object state)
```

**Comment by mhowlett** [comment]
It looks like you're trying to replicate functionality provided by `Consumer.StoreOffsets`, `Config.EnableAutoOffsetStore=false`, `Config.EnableAutoCommit=true` - you might want to consider that approach instead, which will work around this issue.

Commit is quite simple and completely synchronous - i can't think of any reason for what you're observing to be occurring. Marking this as enhancement to make an integration test to replicate.
