### ISSUE TITLE
Enabling SSL results in "Private key check failed: ssl_lib.c:958 ... SSL_CTX_check_private_key:no certificate assigned"

### ISSUE THREAD

**Issue by Fallibilist** [confluentinc/confluent-kafka-dotnet#1062]
Description
===========
Before adding the SSL config we are able to produce without issue.
When building the producer builder with SSL configs set I get the following error:

Unhandled Exception: System.InvalidOperationException: Private key check failed: ssl_lib.c:958: error:140A80B1:SSL routines:SSL_CTX_check_private_key:no certificate assigned:
   at Confluent.Kafka.Impl.SafeKafkaHandle.Create(RdKafkaType type, IntPtr config, IClient owner)
   at Confluent.Kafka.Producer`2..ctor(ProducerBuilder`2 builder)
   at Confluent.Kafka.ProducerBuilder`2.Build()

Config properties:

                    { "security.protocol", "SSL" },
                    { "ssl.ca.location", "/path/ca.pem" },
                    { "ssl.certificate.location","/path/cert.pem" },
                    { "ssl.key.location", "/path/key.pem" },
                    { "ssl.key.password", "password" },

I've verified separately that the files exist and are able to be read. This error seems to exist regardless of whether there is a valid broker, so I don't think the issue is on the broker side. 

If anyone had any insight into what might be causing the issue I would really appreciate the response!

Checklist
=========
Confluent.Kafka nuget version: 1.1.0
OS: Linux Docker Container

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [x] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [x] Operating system.
 - [x] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [x] Critical issue.

**Comment by Fallibilist** [comment]
The certificates needed to be produced in a different format than we were originally producing them. 
This documentation helped us remedy the format issue: https://github.com/mhowlett/confluent-kafka-dotnet/tree/security/examples/Security
