### ISSUE TITLE
Local: Value deserialization error when trying to load assembly System.Runtime.CompilerServices.Unsafe

### ISSUE THREAD

**Issue by christopherread** [confluentinc/confluent-kafka-dotnet#1093]
Description
===========

Getting this exception when trying to consume messages. It appears to be trying to load an assembly version of System.Runtime.CompilerServices.Unsafe (4.0.4) which is different from the one specified in the dependencies (4.5).

Confluent.Kafka.ConsumeException: Local: Value deserialization error ---> System.TypeInitializationException: The type initializer for 'PerTypeValues`1' threw an exception. ---> System.IO.FileLoadException: Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at System.SpanHelpers.PerTypeValues`1.MeasureArrayAdjustment()
   at System.SpanHelpers.PerTypeValues`1..cctor()
   --- End of inner exception stack trace ---
   at Confluent.Kafka.Consumer`2.ConsumeImpl[K,V](Int32 millisecondsTimeout, IDeserializer`1 keyDeserializer, IDeserializer`1 valueDeserializer)
   --- End of inner exception stack trace ---
   at Confluent.Kafka.Consumer`2.ConsumeImpl[K,V](Int32 millisecondsTimeout, IDeserializer`1 keyDeserializer, IDeserializer`1 valueDeserializer)
   at Confluent.Kafka.Consumer`2.Consume(CancellationToken cancellationToken)

How to reproduce
================

Install the latest confluent-kafka-dotnet client package in a project which targets net46 and netstandard2.0 and try to consume messages. I am also using a ProtoBuf deserializer and serializer as described in the examples.

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [x] Confluent.Kafka nuget version 1.2.1
 - [x] Apache Kafka version: https://github.com/wurstmeister/kafka-docker
 - [ ] Client configuration.
 - [x] Operating system: Windows 10
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by christopherread** [comment]
Sorry, found the culprit, it was `Microsoft.Reactive.Testing` that was bringing in a version of `System.Runtime.CompilerServices.Unsafe` that was causing issues.

Once I removed the reference , everything worked.
