### ISSUE TITLE
Setting IsolationLevel to ReadCommitted results in Exception "invalid value"

### ISSUE THREAD

**Issue by stefanloerwald** [confluentinc/confluent-kafka-dotnet#1101]
Description
===========

Confluent.Kafka nuget version 1.2.1, Kafka version: 2.1.1cp1:
Setting the IsolationLevel in a ConsumerConfig triggers the Exception
```
System.ArgumentException
  Message=Invalid value "readcommitted" for configuration property "isolation.level"
  Source=Confluent.Kafka
  StackTrace:
   at Confluent.Kafka.Impl.SafeConfigHandle.Set(String name, String value)
   at Confluent.Kafka.Consumer`2.<>c__DisplayClass67_0.<.ctor>b__3(KeyValuePair`2 kvp)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Confluent.Kafka.Consumer`2..ctor(ConsumerBuilder`2 builder)
   at Confluent.Kafka.ConsumerBuilder`2.Build()
```

How to reproduce
================

```csharp
var consumer_config = new ConsumerConfig 
{
   BootstrapServers = "server:1234",
   GroupId = "group",
   AutoOffsetReset = AutoOffsetReset.Earliest,
   IsolationLevel = IsolationLevel.ReadCommitted
};
using var consumer = new ConsumerBuilder<Ignore, GenericRecord>(consumer_config)
   .SetValueDeserializer(new AvroDeserializer<GenericRecord>(schema_registry).AsSyncOverAsync())
   .Build();
```

**Comment by stefanloerwald** [comment]
Workaround:

```csharp
var consumer_config = new ConsumerConfig 
{
   BootstrapServers = "server:1234",
   GroupId = "group",
   AutoOffsetReset = AutoOffsetReset.Earliest,
   //IsolationLevel = IsolationLevel.ReadCommitted
};
var configs = (IEnumerable<KeyValuePair<string, string>>)consumer_config;
var with_isolation_level = configs.Append(new KeyValuePair<string, string>("isolation.level", "read_committed"));
using var cm = new ConsumerBuilder<Ignore, GenericRecord>(with_isolation_level)
   .SetValueDeserializer(new AvroDeserializer<GenericRecord>(kafka_configuration.SchemaRegistry).AsSyncOverAsync())
   .Build();
```

**Comment by mhowlett** [comment]
thanks for reporting. resolved by: https://github.com/confluentinc/confluent-kafka-dotnet/pull/1098 (will be in v1.3)
