### ISSUE TITLE
Kerberos issue with .net core 2.1 on windows 7 (No such configuration property: "sasl.kerberos.keytab"  )

### ISSUE THREAD

**Issue by zmirza** [confluentinc/confluent-kafka-dotnet#1108]
Description
===========
I'm trying to connect to Kafka brokers using Kerberos and getting following error:

System.InvalidOperationException: No such configuration property: "sasl.kerberos.keytab"
   at Confluent.Kafka.Impl.SafeConfigHandle.Set(String name, String value)
   at Confluent.Kafka.Consumer.<>c__DisplayClass11_0.<.ctor>b__2(KeyValuePair`2 kvp)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Confluent.Kafka.Consumer..ctor(IEnumerable`1 config)
   at Confluent.Kafka.Consumer`2..ctor(IEnumerable`1 config, IDeserializer`1 keyDeserializer, IDeserializer`1 valueDeserializer)

Is there any sample properties available which uses c# .netcore to connect to kafka using kerberos?
I am using latest driver Confluent.Kafka 1.2.1

How to reproduce
================
using (var consumer = new Consumer<Null, string>(consumerConfig, null, new StringDeserializer(Encoding.UTF8)))

{

}

here are the consumer properties that are being used:
bootstrap.servers :"xyc"
auto.offset.reset:"latest"
client.id:"1234"
partition.assignment.strategy:"roundrobin"
security.protocol:"sasl_ssl"
ssl.key.location:"ss.key"
ssl.certificate.location::"ca.pem"
ssl.key.password:"test"
ssl.ca.location:"ca.pem"
sasl.kerberos.principal:"e1234@tyyy.xxx.NET"
sasl.mechanism:"GSSAPI"
sasl.kerberos.service.name:"esaas"
sasl.kerberos.keytab:"XXX.keytab"
sasl.kerberos.kinit.cmd : "kinit -k -t %{sasl.kerberos.keytab} %{sasl.kerberos.principal}"
Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [Confluent.Kafka 1.2.1 ] Confluent.Kafka nuget version.
 - [ confluent 5.2.2] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by meena1977** [comment]
any solution to this. I am also facing the same issues

**Comment by Ankith-Confluent** [comment]
Thanks for reporting this issue.

The version mentioned here is old and no longer supported. If you are still facing this problem with a newer, supported version of the client, please feel free to reopen the issue with updated details, and we’ll be happy to help.

Thanks!
