### ISSUE TITLE
Calling Flush raises a symbol not found exception

### ISSUE THREAD

**Issue by Freds72AtWork** [confluentinc/confluent-kafka-dotnet#111]
Following the producer sample, calling Flush() produces:
Unhandled Exception: System.EntryPointNotFoundException: Unable to find an entry point named 'rd_kafka_flush' in DLL 'librdkafka'.
   at Confluent.Kafka.Impl.LibRdKafka.NativeMethods.rd_kafka_flush(IntPtr rk, IntPtr timeout_ms)
   at Confluent.Kafka.Impl.LibRdKafka.flush(IntPtr rk, IntPtr timeout_ms)
   at Confluent.Kafka.Impl.SafeKafkaHandle.Flush(Int32 millisecondsTimeout)
   at Confluent.Kafka.Producer`2.Flush(Int32 millisecondsTimeout)
   at KafkaPOC.ProducerProgram.MainAsync(String[] args, CancellationToken token) in ...my code....

Using Visual Studio 2017, DotNet Framework 4.5.2, Console Application

**Comment by mhowlett** [comment]
was there a similar problem on instantiation of the producer or when producing messages?

**Comment by Freds72AtWork** [comment]
Both creation and publishing content works fine but for a very short time.

After a couple of seconds (and a few thousand message **successfully** pushed to Kafka), I got:
Unhandled Exception: System.AggregateException: One or more errors occurred. 
---> System.AggregateException: One or more errors occurred. 
---> System.ArgumentOutOfRangeException: The added or subtracted value results in an unrepresentable DateTime.
Parameter name: t
   at System.DateTime.op_Addition(DateTime d, TimeSpan t)
   at Confluent.Kafka.Timestamp.UnixTimestampMsToDateTime(Int64 unixMillisecondsTimestamp)
   at Confluent.Kafka.Producer.DeliveryReportCallbackImpl(IntPtr rk, IntPtr rkmessage, IntPtr opaque)
   at Confluent.Kafka.Impl.LibRdKafka.NativeMethods.rd_kafka_poll(IntPtr rk, IntPtr timeout_ms)
   at Confluent.Kafka.Impl.LibRdKafka.poll(IntPtr rk, IntPtr timeout_ms)
   at Confluent.Kafka.Producer.<>c__DisplayClass9_0.<StartPollTask>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Confluent.Kafka.Producer.Dispose()
   at Confluent.Kafka.Producer`2.Dispose()
   at KafkaPOC.ProducerProgram.MainAsync(String[] args, CancellationToken token) in ...mycode...\ProducerProgram.cs:line 124
   at KafkaPOC.ProducerProgram.<>c__DisplayClass2_0.<Main>b__1() in ...mycode...\ProducerProgram.cs:line 49
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at KafkaPOC.ProducerProgram.Main(String[] args) in ...mycode...\ProducerProgram.cs:line 49

**Comment by mhowlett** [comment]
these errors are new to me... you say this is happening in an example project? can you be a bit more specific about exactly how to reproduce (link to github repo or include code snippet if there are any differences to an example project) and I'll take a look.

**Comment by treziac** [comment]
What package version o you use and what does Confluent.Kafka.VersionString returns?

**Comment by Freds72AtWork** [comment]
Found the root cause, I was using Confluent.Kafka + RdKafka.Internal.librdkafka instead of librdkafka.redist.

Note: Confluent.Kafka.VersionString does not exist in the 0.9.4 version (from Nuget)

**Comment by treziac** [comment]
Meant Confluent.Kafka.Library.VersionString, sorry.
So that's it, you was using an old library -> #115

**Comment by Freds72AtWork** [comment]
(forgive code blindness - I saw the Library.cs code and it didn't click :[
