### ISSUE TITLE
Could not check Schema compatibility: unknown protocol

### ISSUE THREAD

**Issue by vitorapolo** [confluentinc/confluent-kafka-dotnet#1117]
Description
===========

Unable to start KSQL server. 
Error: Could not check Schema compatibility: unknown protocol: cp-shcema-registry-cp-schema-registry
Statement: CREATE TABLE PAGEVIEWS_REGIONS WITH ....

How to reproduce
================
Install KSQL server using an existing kafka cluster and SchemaRegistry:
helm install my-ksql-server -n kafka --set cp-zookeeper.url="my-kafka-zookeeper:2181",cp-schema-registry.url="cp-shcema-registry-cp-schema-registry:8081" cp-ksql-server

Ksql Server didnt start due error: 
Caused by: io.confluent.ksql.util.KsqlException: Could not check Schema compatibility: unknown protocol: cp-shcema-registry-cp-schema-registry
	at io.confluent.ksql.util.AvroUtil.isValidAvroSchemaForTopic(AvroUtil.java:56)

Using KSQL version 5.3.1
SchemaRegistry version: 5.3.1
confluentinc/cp-kafka version: 5.0.1
Apache Kafka version: 2.0.1

Error Log
=========
[2019-11-19 10:16:14,753] ERROR Failed to start KSQL Server with query file: /etc/ksql/queries/queries.sql (io.confluent.ksql.rest.server.StandaloneExecutor:121)
io.confluent.ksql.util.KsqlStatementException: Could not check Schema compatibility: unknown protocol: cp-shcema-registry-cp-schema-registry
Statement: CREATE TABLE PAGEVIEWS_REGIONS WITH (REPLICAS = 1, PARTITIONS = 4, VALUE_FORMAT = 'avro', KAFKA_TOPIC = 'PAGEVIEWS_REGIONS') AS SELECT
  PAGEVIEWS_ENRICHED.GENDER "GENDER"
, PAGEVIEWS_ENRICHED.REGIONID "REGIONID"
, COUNT(*) "NUMUSERS"
FROM PAGEVIEWS_ENRICHED PAGEVIEWS_ENRICHED
WINDOW TUMBLING ( SIZE 30 SECONDS ) 
GROUP BY PAGEVIEWS_ENRICHED.GENDER, PAGEVIEWS_ENRICHED.REGIONID
HAVING (COUNT(*) > 1);
	at io.confluent.ksql.engine.EngineExecutor.execute(EngineExecutor.java:114)
	at io.confluent.ksql.engine.SandboxedExecutionContext.execute(SandboxedExecutionContext.java:97)
	at io.confluent.ksql.engine.SandboxedExecutionContext.execute(SandboxedExecutionContext.java:86)
	at io.confluent.ksql.rest.server.StandaloneExecutor$StatementExecutor.handlePersistentQuery(StandaloneExecutor.java:335)

Checklist
=========

Please provide the following information:
 - [x] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [x] Confluent.Kafka nuget version.
 - [x] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [x] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
this issue is unrelated to the .net client.

.. but it looks like you're not specifying a url when you need to since it's complaining that 'cp-shcema-registry-cp-schema-registry' is not a valid protocol (i.e. http or https). a valid schema registry url would be something like "http://localhost:8081" (but the domain or ip depends on your setup).

Also, schema is spelled incorrectly in `cp-shcema-registry-cp-schema-registry`.
