### ISSUE TITLE
Confluent.Kafka.ConsumeException: Local: Broker transport failure

### ISSUE THREAD

**Issue by SmAnbu** [confluentinc/confluent-kafka-dotnet#1146]
Description
===========

We are experiencing the below error intermittently 

Confluent.Kafka.ConsumeException: Local: Broker transport failure     at Confluent.Kafka.Consumer`2.ConsumeImpl[K,V](Int32 millisecondsTimeout, IDeserializer`1 keyDeserializer, IDeserializer`1 valueDeserializer)     at Confluent.Kafka.Consumer`2.Consume(CancellationToken cancellationToken)     at 
 

just want to know whether this issue related to  timeout or some other issue?
If in case timeout related then i can ignore this issue.
If other type of issue means how to handle? 

How to reproduce
================

This issue is intermittent issue.  
Session time out in the consumer config : 
SessionTimeoutMs = 100000
other configurations are default 

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ ] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by yinbiaoh** [comment]
I have same issue.

Local: Broker transport failure
Confluent.Kafka.ConsumeException: Local: Broker transport failure
   at Confluent.Kafka.Consumer`2.ConsumeImpl[K,V](Int32 millisecondsTimeout, IDeserializer`1 keyDeserializer, IDeserializer`1 valueDeserializer)
   at Confluent.Kafka.Consumer`2.Consume(CancellationToken cancellationToken)

Same code works without issue on other machines

**Comment by mhowlett** [comment]
I believe this is a retriable error that librdkafka is incorrectly exposing to the application, but which it is otherwise handling correctly. I believe there will be no adverse effects to just ignoring it.

fyi: @edenhill - need to fix this.

**Comment by moecia** [comment]
We have the same issue. Any updates on that?

**Comment by johnkwaters** [comment]
Fixed yet?

**Comment by mhowlett** [comment]
i don't think so

**Comment by jbressand** [comment]
Hello,  same issue here, any updates ?

**Comment by jbressand** [comment]
same issue here, any updates ?

**Comment by dvlprx** [comment]
Same issue
