### ISSUE TITLE
How to get details of non-transient exceptions?

### ISSUE THREAD

**Issue by wags1999** [confluentinc/confluent-kafka-dotnet#1236]
Description
===========
.NET 4.7.2
Client = Confluent.Kafka 1.3 or 1.4
Broker = Confluent Kafka 5.3.1
Client OS = Windows 10

I'm trying to write a simple program to produce messages.  Some sample code is below.  If I have the BootstrapServers wrong, or the Topic wrong, or don't have access to the topic, the program simply waits until the MessageTimeoutMs expires, and then gives this generic exception:

    Confluent.Kafka.ProduceException``2
      HResult=0x80131500
      Message=Local: Message timed out
      Source=Confluent.Kafka
      StackTrace:
       at Confluent.Kafka.Producer``2.<ProduceAsync>d__52.MoveNext()
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter``1.GetResult()

The only way that I have found that I can get info about why the message timed out is by turning on Debug = "all".  But then all I get is a "debug" message.  For example, when I tried producing to a topic that doesn't exist ("NONEXISTENT") using the code below, I get 288 debug messages logged - a couple of them include:

    DEBUG from Kafka: [thrd:main]: Error in metadata reply for topic NONEXISTENT (PartCnt 0): Broker: Topic authorization failed

Setting Debug = "all" isn't practical in a server environment, so I'm concerned about being able to know why something is failing in a server environment when it fails.

**What am I doing wrong?**  This seems similar to the discussion on #203, but there's been no activity on that since 2017.  One [suggestion I found](https://github.com/confluentinc/confluent-kafka-dotnet/issues/1057#issuecomment-553897322) is to use an AdminClient to call GetMetaData when the application starts up - is that recommended?

How to reproduce
================
Here's some sample code whereby you can recreate this:

    public class Program
    {
        public static async Task Main(string[] args)
        {
            string brokerList = args[0];
            string topicName = args[1];
    
            var config = new ProducerConfig
            {
                BootstrapServers = brokerList,
                MessageTimeoutMs = 5000,
                Debug = "all",
                SecurityProtocol = SecurityProtocol.SaslSsl,
                SaslMechanism = SaslMechanism.Gssapi,
                SaslKerberosServiceName = "cp-kafka"
            };
    
            using (var producer = new ProducerBuilder<string, string>(config).
                 SetLogHandler((x, y) => Console.WriteLine($"{Enum.GetName(typeof(SyslogLevel), y.Level).ToUpper()} from Kafka: {y.Message}")).
                 SetErrorHandler((c, e) => Console.WriteLine($"{(e.IsFatal ? "FATAL" : "ERROR")} from Kafka: Code {e.Code}; Reason {e.Reason}")).
                 Build())
            {
                var deliveryReport = await producer.ProduceAsync(
                    topicName,
                    new Message<string, string> { Key = "myKey", Value = "myValue" });

                Console.WriteLine($"Successfully delivered to: {deliveryReport.TopicPartitionOffset}");
            }

            Console.WriteLine("Press any key to end.");
            Console.ReadKey();
        }
    }

Checklist
=========

Please provide the following information:
 - [X] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [X] Confluent.Kafka nuget version.
 - [X] Apache Kafka version.
 - [X] Client configuration.
 - [X] Operating system.
 - [X] Provide logs (with "debug" : "..." as necessary in configuration).
 - [X] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
> If I have the BootstrapServers wrong, or the Topic wrong, or don't have access to the topic, the program simply waits until the MessageTimeoutMs expires

yes, the client assumes the user isn't making errors like this. i agree that this isn't ideal because in practice, this happens frequently. we may improve this in the future but for now, yes, use whatever tools you have available (admin client, metadata request) to achieve what you need.

**Comment by wags1999** [comment]
Thanks for the quick response, @mhowlett.  Might I suggest for the short term that making an AdminClient.GetMetaData call get added to some of the examples?

**Comment by mhowlett** [comment]
thanks for the suggestion. i think the path forward will be different (add a blocking client creation api), and i don't think we'll add the metadata request idea to the examples in the interim.
