### ISSUE TITLE
Confluent.Kafka.ConsumeException: Broker: Unsupported compression type 

### ISSUE THREAD

**Issue by klesta490** [confluentinc/confluent-kafka-dotnet#1253]
Description
===========
I have producer producing messages using **zstd** compression.
Consumer fails to consume message when **zstd** compression is set on topic.
When I leave topic in default configuration (compression=producer) it works. 

Smells like this https://github.com/edenhill/librdkafka/pull/2183  but this should be already fixed.
What am I doing wrong?

How to reproduce
================
Create topic with zstd compression.
Produce message with zstd.
Try Consume this message.
 
```
Confluent.Kafka.ConsumeException: Broker: Unsupported compression type
   at Confluent.Kafka.Consumer`2.Consume(Int32 millisecondsTimeout)
   at Confluent.Kafka.Consumer`2.Consume(TimeSpan timeout)
```

Checklist
=========

Please provide the following information:
 - [x] Apache Kafka version. 2.2.0 
 - [x] Operating system. Linux/Windows
 - [x] kafka-dotnet 1.4.0

**Comment by mhowlett** [comment]
it might be worth checking you're not accidentally referencing and old version of librdkafka by looking at the result of `Library.VersionString` in your application.

other than that i don't have any good ideas except keep swapping things out until it works so as to narrow in on the problem. i.e. try with newer broker. try client on different platform. etc.

did a quick test and produce/consume with zstd works for me (on linux, kafka 2.3).

**Comment by milindl** [comment]
Closing this as it's been awaiting info for a while. If it persists, please reopen it with the stuff Matt asked for, and with the latest version of the client.
