### ISSUE TITLE
Consume exception - Value deserialization error

### ISSUE THREAD

**Issue by Realsnack** [confluentinc/confluent-kafka-dotnet#1275]
Description
===========
I am currently trying to resolve an Value deserialization error when trying to consume a message from my Kafka.

Kafka: 2.12-2.5.0 (Tried on Confluent platform on 5.5.0 - still same)

Nuggets:
Confluent.Kafka 1.4.2
Confluent.SchemaRegistry 1.4.2
Confluent.SchemaRegistry.Serdes.Avro 1.4.2

I know that my message is not null because for testing purpouse its sent by my program.

How to reproduce
================
```
using (var consumer = new ConsumerBuilder<int, KafkaModels.DomesticPaymentRequest>(_consumerConfig)
                .SetValueDeserializer(new AvroDeserializer<KafkaModels.DomesticPaymentRequest>(_schemaRegistry).AsSyncOverAsync()).Build())
            {
                try
                {
                    while (!stoppingToken.IsCancellationRequested)
                    {
                        Confluent.Kafka.Message<int, KafkaModels.DomesticPaymentRequest> consumeResult = null;
                        consumer.Subscribe(_topic);
                        try
                        {
                            consumeResult = consumer.Consume().Message;
                        }
                        catch (System.Exception ex)
                        {
                            _logger.LogError(ex, "Error:");
                        }

                        if (consumeResult.Value != null)
                            _logger.LogDebug($"{DateTime.Now.ToString("hh.mm.ss.FFF")}\tConsumed message: {consumeResult.Value.Source} with key: {consumeResult.Key}");
                        else
                            _logger.LogDebug("Null value message");
                    }
                    consumer.Close();
                }
                catch (System.Exception ex)
                {
                    _logger.LogError(ex, "KafkaConsumer error:");
                }
            }
        }
```

Log output:
```
fail: RESTAdapter.Services.KafkaConsumerService[0]
      Error:
Confluent.Kafka.ConsumeException: Local: Value deserialization error
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Confluent.SchemaRegistry.Serdes.SpecificDeserializerImpl`1.Deserialize(String topic, Byte[] array)
   at Confluent.SchemaRegistry.Serdes.AvroDeserializer`1.DeserializeAsync(ReadOnlyMemory`1 data, Boolean isNull, SerializationContext context)
   at Confluent.Kafka.SyncOverAsync.SyncOverAsyncDeserializer`1.Deserialize(ReadOnlySpan`1 data, Boolean isNull, SerializationContext context)
   at Confluent.Kafka.Consumer`2.Consume(Int32 millisecondsTimeout)
   --- End of inner exception stack trace ---
   at Confluent.Kafka.Consumer`2.Consume(Int32 millisecondsTimeout)
   at Confluent.Kafka.Consumer`2.Consume(CancellationToken cancellationToken)
   at RESTAdapter.Services.KafkaConsumerService.StartConsumer(CancellationToken stoppingToken) in /Users/michalsvacina/Projects/Microservice/MicroservicesProject/src/RESTAdapter/Services/KafkaConsumerService.cs:line 49
fail: RESTAdapter.Services.KafkaConsumerService[0]
      KafkaConsumer error:
System.NullReferenceException: Object reference not set to an instance of an object.
   at RESTAdapter.Services.KafkaConsumerService.StartConsumer(CancellationToken stoppingToken) in /Users/michalsvacina/Projects/Microservice/MicroservicesProject/src/RESTAdapter/Services/KafkaConsumerService.cs:line 56
```

**Comment by mhowlett** [comment]
it's hard to say without line numbers. Suggest running in the debugger and setting a breakpoint in `SpecificDeserializerImpl`. To do this, you could fetch the confluent-kafka-dotnet project from github, edit the Consumer example to read your data type, then debug that.

**Comment by Realsnack** [comment]
Sorry the line 56 is the line
`consumeResult = consumer.Consume().Message;`

**Comment by mhowlett** [comment]
line numbers inside `SpecificDeserializerImpl`

**Comment by Realsnack** [comment]
Okay I just found out what the error was.

1. I didn't have the CachedSchemaRegistryClient initialized - feel like an idiot.
2. For some reason my Kafka model needed a parameterless constructor in my Api template (in console application this is not needed?)

Thanks for help anyways.

**Comment by mhowlett** [comment]
it would be better if we threw a better exception in this case, but minor enhancement.
