### ISSUE TITLE
Null Ref Exception when mixing custom and Avro Serializers

### ISSUE THREAD

**Issue by bobcat1506** [confluentinc/confluent-kafka-dotnet#1282]
Description
===========
When using a combination of a custom and an Avro serializer the producer encounters a Null Reference Exception.
```
Exception has occurred: CLR/System.NullReferenceException
An exception of type 'System.NullReferenceException' occurred in System.Private.CoreLib.dll but was not handled in user code: 'Object reference not set to an instance of an object.'
   at ConfluentNullRef.AvroEnqueuer.<EnqueueAsync>d__3.MoveNext() in /home/administrator/Documents/src/ConfluentNullRef/ConfluentNullRef/AvroEnqueuer.cs:line 21
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at ConfluentNullRef.Program.<Main>d__0.MoveNext() in /home/administrator/Documents/src/ConfluentNullRef/ConfluentNullRef/Program.cs:line 22
```
How to reproduce
================

1. Clone this repo: https://github.com/bobcat1506/ConfluentNullRef
1. Run docker-compose up -d
1. Run docker exec -it broker kafka-topics --bootstrap-server localhost:9092 --create --topic test-topic
1. Run the console app

**Comment by mhowlett** [comment]
I haven't looked closely, but it looks like it could be a problem in the Avro implementation. Can you resolve the problem by changing the schema to something very simple? If so, suggest opening an issue on the avro repo, or switching to protobuf or json (which have very good implementations in .net)

**Comment by bobcat1506** [comment]
> I haven't looked closely, but it looks like it could be a problem in the Avro implementation. Can you resolve the problem by changing the schema to something very simple? If so, suggest opening an issue on the avro repo, or switching to protobuf or json (which have very good implementations in .net)

I updated the sample with a simpler schema, but still getting the same error.  Let me know if I should still open an issue with the Avro repo or if this is still valid in this repo.  I will also take a look at protobuf as well.

**Comment by mhowlett** [comment]
again, looking very quickly - the stack trace doesn't extend inside Confluent.Kafka - it looks like you never set your `producer` variable to a value.

**Comment by bobcat1506** [comment]
Your right the producer was never set, that was a pretty boneheaded mistake.  We have a separate code base currently getting a value serialization error, and I'm trying to replicate it on a machine on a completely different network. When I saw the null reference I didn't check close enough to ensure I'd replicated it.

When I updated the sample it now runs fine, so I will keep trying to replicate what is going on in our other code base. When I am able to replicate it I will update the repo and this issue.

This is what we are seeing in our other code base (I typed this rather than copy/pasted).  We have validated the producer has the key and value serializers set and the message we are passing in has the key and values set.  

```
Message:
Confluent.Kafka.ProduceException`2[System.Guid,MessageTypes.LogMessage] : Local: Value serialization error
----> System.NullReferenceException : Object reference not set to an instance of an object.

StackTrace:
Producer.ProduceAsync[TopicPartition topicPartition, Message`2 message, CancellationToken cancellationToken)  
KafkaMessageEnqueuerBase`1.EnqueueMessageAsync(KafkaMessage`1 message) line 80
....
```

**Comment by bobcat1506** [comment]
The issue was in our inheritance. Essentially the producer was being created before the ISchemaRegistryClient, so the instance being passed into the AvroSerializer was null.

I've updated the repo to reproduce the problem.  IMO the AvroSerializer should throw a more intuitive error indicating when the ISchemaRegistryClient is null rather than a generic Value serialization error.

**Comment by mhowlett** [comment]
We should improve the InnerException to be more informative.

I understand your point about the generic value serialization error, and agree a more specific top level exception would be better. it's a little harder to arrange for though, so i'm not sure if we'll do it.
