### ISSUE TITLE
Unable to produce messages to Topic

### ISSUE THREAD

**Issue by BibhutiBhusanDora** [confluentinc/confluent-kafka-dotnet#1306]
Description
===========
I have a client bases on .net framework and it has the code to produce message to a Kakfa topic. We had demonstrated the same code on development enviromnet and it was working fine . But after today's production release, the client is not able to produce to Topic. It is giving below exception.

The code for producing message to topic is a dll developed by another team and they are using Confluent.Kafka 1.2.2 . My client was already using  Confluent.Kafka.StrongName 1.0.0. Hence, we have done a run time assembly binding from my client to 1.2.2. I am seeing multiple X64,X86 folder in bin. One inside librdkafka folder and 2 standalone folders named x64 & x86. Screenshot attached.

```
020-06-04 10:27:24.4876][Offerings.FailureRequeue.Helpers.LogHelper][ERROR][TransactionId:]Exception Occured While Sending message to Kafka Topic and the Exception Message is: Unable to find an entry point named 'rd_kafka_headers_new' in DLL 'librdkafka'. and Stack Trace is:   at Confluent.Kafka.Impl.NativeMethods.NativeMethods.rd_kafka_headers_new(IntPtr size)
   at Confluent.Kafka.Impl.SafeKafkaHandle.marshalHeaders(IEnumerable`1 headers)
   at Confluent.Kafka.Impl.SafeKafkaHandle.Produce(String topic, Byte[] val, Int32 valOffset, Int32 valLength, Byte[] key, Int32 keyOffset, Int32 keyLength, Int32 partition, Int64 timestamp, IEnumerable`1 headers, IntPtr opaque)
   at Confluent.Kafka.Producer`2.ProduceImpl(String topic, Byte[] val, Int32 valOffset, Int32 valLength, Byte[] key, Int32 keyOffset, Int32 keyLength, Timestamp timestamp, Partition partition, IEnumerable`1 headers, IDeliveryHandler deliveryHandler)
   at Confluent.Kafka.Producer`2.<ProduceAsync>d__51.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Offerings.FailureRequeue.Helpers.Kafka.<SendMsgToKafkaTopicAsync>d__17.MoveNext() in D:\CI\jenkins-node\workspace\Collections_DP\Release-OfferingsNew-Compile\Offerings.FailureRequeue\Helpers\Kafka.cs:line 82  
  
```

How to reproduce
================

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ ] Confluent.Kafka nuget version. Confluent.Kafka 1.2.2
 - [ ] Apache Kafka version. 1.0.0
 - [ ] Client configuration. .net 4.5.2 
 - [ ] Operating system. Windows Server 2012
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
it looks like a librdkafka version mismatch (new version of Confluent.Kafka has loaded and is trying to use an old version of librdkafka). suggest aligning versions (preferably to latest version). this specific scenario is something I don't think we'll get time to address.

**Comment by BibhutiBhusanDora** [comment]
Thanks.
In the development environment where we had demonstrated this code working properly, we are using Confluent.Kafka.StrongName, but in Production we are using Confluent.Kakfa.
That is why am seeing additional 2 folders x64 & x86 in bin when I use Confluent.Kafka.
I will try updating the packages and hope that will fix the issue.
