### ISSUE TITLE
Cannot setup simple producer in SSIS script component

### ISSUE THREAD

**Issue by noelfoster78** [confluentinc/confluent-kafka-dotnet#131]
I am trying to setup a simple producer using the code in the example file in an SSIS script component in VS2013 with SQL BI SSDT tools. The script component cannot use external libraries from nuget so I have registered the libraries in the GAC for conluent.kafka.dll and RdKafka.dll. When I try to execute the script in de-bug I get the following error:

at Confluent.Kafka.Impl.LibRdKafka.conf_new()
   at Confluent.Kafka.Impl.SafeConfigHandle.Create()
   at Confluent.Kafka.Producer..ctor(IEnumerable`1 config, Boolean manualPoll, Boolean disableDeliveryReports)
   at Confluent.Kafka.Producer`2..ctor(IEnumerable`1 config, ISerializer`1 keySerializer, ISerializer`1 valueSerializer, Boolean manualPoll, Boolean disableDeliveryReports)
   at ScriptMain.Input0_ProcessInputRow(Input0Buffer Row)
   at UserComponent.Input0_ProcessInput(Input0Buffer Buffer)
   at UserComponent.ProcessInput(Int32 InputID, String InputName, PipelineBuffer Buffer, OutputNameMap OutputMap)
   at Microsoft.SqlServer.Dts.Pipeline.ScriptComponent.ProcessInput(Int32 InputID, PipelineBuffer buffer)
   at Microsoft.SqlServer.Dts.Pipeline.ScriptComponentHost.ProcessInput(Int32 inputID, PipelineBuffer buffer)

I think that my issue has something to do with the libraries in the GAC since I was able to get a console app to work with the same code. Has anyone got a script component to work using this project?

**Comment by treziac** [comment]
You mean linrdkafka and zlib right? 

You can't put unmanaged lib in the GAC from my knowledge.
You will have to either:
- put the dll in the folder where the application is launch (I don't know where this is with ssis)
- put the x64 dlls in Windows/system32 and x86 in sysWOW64
- load the dll manually with another mean (again don't know ssis enough for this)

The second way seems the easier for you. It has downsides (you can't have multiple versions of the all this way)  but should do the job

**Comment by noelfoster78** [comment]
Thanks! I tried option 2 first and it worked so I did not try the other options. So the way I got it to work was to register conluent.kafka.dll and RdKafka.dll in the GAC (I had to add a strong name using the directions in this link http://www.geekzilla.co.uk/ViewCE64BEF3-51A6-4F1C-90C9-6A76B015C9FB.htm ). After that I added the 32 and 64 bit versions in the correct place in the Windows dir of librdkafka.dll and zlib.dll. Once again thanks for the help.

**Comment by treziac** [comment]
You don't need Rdkafka.dll (it was the former project confluent-kafka-dotnet is baed on)

Ensure that you registered the correct librdkafka.dll and zlib version (should be 0.9.4) or you will have issues (some functions,  like flush, will throw) If you copied the dll from Rdkafka.Internal, it's wrong, you must copy the one from librdkafka.redist (there seems to be a bug in vs2013, you might have to unpack the librdkafka.nupkg by yourself) Must be related to end of #123
