### ISSUE TITLE
Exception after partition number increasing

### ISSUE THREAD

**Issue by IgorPikul** [confluentinc/confluent-kafka-dotnet#1345]
Description
===========
Unexpected behavior during changing partition number. 
At the beginning of the test I have one producer, kafka topic with 1 partition and 2 consumers in the same consumer group with manual offset store.
During permanent producing of items to kafka I increased number of partitions up to 4. After that active consumer triggered OnPartitionsRevoked event which I handle performing the following calls:  
	_consumer.Unassign(); 
	_consumer.CommitAsync();
How to reproduce
================
Then I got three different program continuations (the same test case gives 3 different results).

1. OnPartitionsRevoked event is triggered with 2 partitions for consumer that was active before topic altering. 
	   I call _consumer.Committed(partitionList, Timeout) for these partitions, and then call _consumer.QueryWatermarkOffsets(tpoe.TopicPartition, Timeout).
	   Then OnPartitionsRevoked event is triggered  with 2 other partitions for consumer that was stand by before topic altering. 
	   I aslo call _consumer.Committed(partitionList, Timeout) for those partitions and then during call
	   _consumer.QueryWatermarkOffsets(tpoe.TopicPartition, Timeout);  I got 
	   Confluent.Kafka.KafkaException
	   HResult=0x80131500   
	   Message=Local: Unknown partition  
	   Source=Confluent.Kafka
	   StackTrace:
		at Confluent.Kafka.Impl.SafeKafkaHandle.QueryWatermarkOffsets(String topic, Int32 partition, Int32 millisecondsTimeout)
		at Confluent.Kafka.Consumer.QueryWatermarkOffsets(TopicPartition topicPartition, TimeSpan timeout)
		at BetLab.Kafka.KafkaConsumer.<>c__DisplayClass21_0.<ConsumeFrom>b__2(TopicPartitionOffsetError tpoe)
		at System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource x)
		at System.Linq.Enumerable.WhereSelectListIterator`2.ToList()
		at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
		at System.Linq.Enumerable.<SelectManyIterator>d__167`3.MoveNext()
		at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
		at System.Collections.Generic.HashSet`1..ctor(IEnumerable`1 collection, IEqualityComparer`1 comparer)
		at System.Collections.Generic.HashSet`1..ctor(IEnumerable`1 collection)
		at BetLab.Common.EnumerableExtension.ToHashSet[T](IEnumerable`1 collection)
		at BetLab.Kafka.KafkaConsumer.OnPartitionsAssigned(Object sender, List`1 topicPartitions)
		at Confluent.Kafka.Consumer.RebalanceCallback(IntPtr rk, ErrorCode err, IntPtr partitions, IntPtr opaque)
		at Confluent.Kafka.Impl.NativeMethods.NativeMethods.rd_kafka_consumer_poll(IntPtr rk, IntPtr timeout_ms)
		at Confluent.Kafka.Impl.SafeKafkaHandle.ConsumerPoll(Message& message, IntPtr millisecondsTimeout)
		at Confluent.Kafka.Consumer.Consume(Message& message, Int32 millisecondsTimeout)
		at Confluent.Kafka.Consumer.Poll(TimeSpan timeout)
		at BetLab.Kafka.KafkaConsumer.<InternalInitialize>b__34_0()
		at System.Threading.Thread.ThreadMain_ThreadStart()
		at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
		at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

2. OnPartitionsRevoked event is triggered with 1 or 2 partitions([0] or [0] and one new partition ) for consumer that was active before topic altering. 
	   I call _consumer.Committed(partitionList, Timeout) for this partitions, and then get watermarks using QueryWatermarkOffsets. 
	   But OnPartitionsRevoked event don't triggered for other consumer.

3. OnPartitionsRevoked event is triggered for both consumers and partition are assigned correctly, but only one consumer, that was active before topic altering, got message hovewer messages are produce to all partitions.

Checklist
=========
.net core version: 3.1
Confluent.Kafka: Confluent.Kafka, Version=0.11.4.0
Alter kafka topic with command: ~\windows\kafka-topics.bat --zookeeper zookeeperHost:2181 --alter --topic sportsbook-test --partitions 4
		WARNING: If partitions are increased for a topic that has a key, the partition logic or ordering of the messages will be affected
		Adding partitions succeeded!
kafka-topics.bat is loaded from: https://www.apache.org/dyn/closer.cgi?path=/kafka/2.5.0/kafka_2.12-2.5.0.tgz

Can you share any details about partition reassigning during message processing, is it safe to change partition count during processing?
Also, can you provide any details about error that I got (Local: Unknown partition)?

**Comment by Ankith-Confluent** [comment]
Thanks for reporting this.

The version used here (Confluent.Kafka 0.11.4.0) is very old and no longer supported, the API and consumer group handling have changed significantly since then. If you are still experiencing issues with dynamic partition changes on a current version of the client, please feel free to open a new issue with updated details.

Closing this out.

Thanks!
