### ISSUE TITLE
How to set acks property to get full acknowledgement on producer end?

### ISSUE THREAD

**Issue by vinodres** [confluentinc/confluent-kafka-dotnet#135]
How should I set acks property while creating an instance of Producer<string, string> ? I would like to get guaranteed acknowledgement while publishing a message.

I have tried 

```
var config = new Dictionary<string, object>
            {
                { "bootstrap.servers", brokerList },
                { "client.id", "Test.Client.001" },
                { "acks", -1 }, //????
            };
using (var producer = new Producer<string, string>(config, new StringSerializer(Encoding.UTF8), new StringSerializer(Encoding.UTF8)))
{
   Console.WriteLine($"Producer {producer.Name} producing on topic {topicName}.");
}
```

And I am receiving following error
Unhandled Exception: System.InvalidOperationException: No such configuration property: "acks"
   at Confluent.Kafka.Impl.SafeConfigHandle.Set(String name, String value)
   at Confluent.Kafka.Producer.<>c__DisplayClass22_0.<.ctor>b__2(KeyValuePair`2 kvp)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Confluent.Kafka.Producer..ctor(IEnumerable`1 config, Boolean manualPoll, Boolean disableDeliveryReports)
   at Confluent.Kafka.Producer`2..ctor(IEnumerable`1 config, ISerializer`1 keySerializer, ISerializer`1 valueSerializer, Boolean manualPoll, Boolean disableDeliveryReports)
   at Confluent.Kafka.Producer`2..ctor(IEnumerable`1 config, ISerializer`1 keySerializer, ISerializer`1 valueSerializer)
   at TestProducer.Program.Main(String[] args) in 

I am trying to create a test producer using c#, .NET 4.6.1 and I am using Confluent.Kafka 0.9.4, librdkafka.redist 0.9.4.

**Comment by treziac** [comment]
acks is a topic configuration.
You have to set this:

```
var config = new Dictionary<string, object>
            {
                { "bootstrap.servers", brokerList },
                { "client.id", "Test.Client.001" },
                { "default.topic.config", new Dictionary<string, object>()
                    {
                        { "acks", -1 }
                    }
                }
            };
```

**Comment by mhowlett** [comment]
whoops didn't mean to close that right away, meant to press cancel. Anyway - @treziac you beat me to it - yes, this is a topic level property.
