### ISSUE TITLE
arm64 bug report

### ISSUE THREAD

**Issue by CrazyJson** [confluentinc/confluent-kafka-dotnet#1359]
Hello, I manually compiled librdKafka ARM64 version of so file, the program boot times the following exception

`Unhandled exception. System.InvalidOperationException: No such configuration property: "client.software.name"
   at Confluent.Kafka.Impl.SafeConfigHandle.Set(String name, String value) in E:\xx\CANetLibvip\Confluent.Kafka\Impl\SafeConfigHandle.cs:line 116
   at Confluent.Kafka.Producer`2.<>c__DisplayClass51_0.<.ctor>b__4(KeyValuePair`2 kvp) in E:\xx\CANetLibvip\Confluent.Kafka\Producer.cs:line 620
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Confluent.Kafka.Producer`2..ctor(ProducerBuilder`2 builder) in E:\xx\CANetLibvip\Confluent.Kafka\Producer.cs:line 617
   at Confluent.Kafka.ProducerBuilder`2.Build() in E:\xx\CANetLibvip\Confluent.Kafka\ProducerBui`

Trying to reference the source code comment NameAndVersionConfig configuration, a new exception appears
`   internal static List<KeyValuePair<string, string>> NameAndVersionConfig
        {
            get
            {
                return new List<KeyValuePair<string, string>>
                {
                    new KeyValuePair<string, string>( "client.software.name", "confluent-kafka-dotnet"),
                    new KeyValuePair<string, string>( "client.software.version", VersionString )
                };
            }
        }`

`[root@arm-253 kafkatest]# dotnet KafakTest.dll
bootstrap.servers---192.168.10.10:21005,192.168.10.11:21005,192.168.10.12:21005
%3|1595321326.325|FAIL|rdkafka#producer-1| [thrd:192.168.10.11:21005/bootstrap]: 192.168.10.11:21005/bootstrap: Connect to ipv4#192.168.10.11:21005 failed: Connection refused
%3|1595321326.325|ERROR|rdkafka#producer-1| [thrd:192.168.10.11:21005/bootstrap]: 192.168.10.11:21005/bootstrap: Connect to ipv4#192.168.10.11:21005 failed: Connection refused
`

**Comment by CrazyJson** [comment]
The same code runs on a Linux X64 server without any problems

`[root@elk197 kafkatest]# dotnet KafakTest.dll
Delivered 'test' to 'test-topic [[0]] @1'
`

**Comment by mhowlett** [comment]
the `client.software.name` config is relatively new - you're probably compiling an old version of librdkafka.
