### ISSUE TITLE
"Specified group generation id is not valid" in First Commit

### ISSUE THREAD

**Issue by dogac00** [confluentinc/confluent-kafka-dotnet#1435]
Description
===========

When our application starts and consumer starts consuming messages, in first commit, we get "*Broker: Specified group generation id is not valid*". After that, in other commits, we do not get any error messages. This only occurs in startup of the program. I don't think anything is wrong with our group id. Also, when we look at Kafka Manager we can see our consumer group id and our consumer group is consuming messages just fine. Any idea what might be the cause of this? Does this error take down the consumer? This situation only occurs in our production cluster, not in our development and staging cluster.

The logged error is this:
```
2020-10-23 08:28:43.0462|ERROR|Service.Consumers.Order.OrderConsumer|Confluent.Kafka.KafkaException: Broker: Specified group generation id is not valid
   at Confluent.Kafka.Impl.SafeKafkaHandle.Commit(IEnumerable`1 offsets)
   at Confluent.Kafka.Consumer`2.Commit(ConsumeResult`2 result)
   at Service.Consumers.ConsumerBase.KafkaConsumer.Run(CancellationToken cancellationToken) in /src/src/Consumers/ConsumerBase/KafkaConsumer.cs:line 48
```

Our consumer configuration:
``` cs
new ConsumerConfig
                    {
                        BootstrapServers = "our-bootstrap-servers",
                        GroupId = "our-group-id",
                        EnableAutoCommit = false,
                        StatisticsIntervalMs = 5000,
                        SessionTimeoutMs = 6000,
                        AutoOffsetReset = AutoOffsetReset.Earliest,
                        EnablePartitionEof = true
                    }
```
Our consume loop:
``` cs
public void Run(CancellationToken cancellationToken)
{
    while (!cancellationToken.IsCancellationRequested)
    {
        var consumeResult = null as ConsumeResult<string, string>;

        try
        {
            _consumer.Subscribe(_topic);

            while (!cancellationToken.IsCancellationRequested)
            {
                consumeResult = _consumer.Consume(cancellationToken);

                if (consumeResult?.Message == null)
                {
                    continue;
                }

                // Process message here

                if (consumeResult.Offset % _commitPeriod == 0)
                {
                    _consumer.Commit(consumeResult);
                }
            }
        }
        catch (Exception e)
        {
             // Log message here
        }
    }
}
```

I reproduced this in my local environment with logs set to `debug: all` configuration. Here is the log of the given error:
```
info: Service.Consumers.OrderCreated.OrderCreatedConsumer[0]
      OrderCreatedConsumer Log, Level : Debug, Message : [thrd:main]: OUR_BOOTSTRAP_SERVERS/2: Joining group "orderCreated" with 1 subscribed topic(s)
info: Service.Consumers.OrderCreated.OrderCreatedConsumer[0]
      OrderCreatedConsumer Log, Level : Debug, Message : [thrd:main]: Group "orderCreated" changed join state init -> wait-join (v1, state up)
info: Service.Consumers.OrderCreated.OrderCreatedConsumer[0]
      OrderCreatedConsumer Log, Level : Debug, Message : [thrd:GroupCoordinator]: GroupCoordinator/2: Sent JoinGroupRequest (v5, 170 bytes @ 0, CorrId 4)
info: Service.Consumers.OrderCreated.OrderCreatedConsumer[0]
      OrderCreatedConsumer Log, Level : Debug, Message : [thrd:GroupCoordinator]: Broadcasting state change
info: Service.Consumers.OrderCreated.OrderCreatedConsumer[0]
      OrderCreatedConsumer Log, Level : Debug, Message : [thrd:GroupCoordinator]: GroupCoordinator/2: Received JoinGroupResponse (v5, 64 bytes, CorrId 4, rtt 50.33ms)
info: Service.Consumers.OrderCreated.OrderCreatedConsumer[0]
      OrderCreatedConsumer Log, Level : Debug, Message : [thrd:main]: JoinGroup response: GenerationId -1, Protocol , LeaderId , my MemberId rdkafka-c6180872-7e7f-4f7a-a470-fa51bd6beab4, 0 members in group: Broker: Group member needs a valid member ID
info: Service.Consumers.OrderCreated.OrderCreatedConsumer[0]
      OrderCreatedConsumer Log, Level : Debug, Message : [thrd:main]: GroupCoordinator/2: JoinGroupRequest failed: Broker: Group member needs a valid member ID: explicit actions Ignore
info: Service.Consumers.OrderCreated.OrderCreatedConsumer[0]
      OrderCreatedConsumer Log, Level : Debug, Message : [thrd:main]: Group "orderCreated": updating member id "" -> "rdkafka-c6180872-7e7f-4f7a-a470-fa51bd6beab4"
info: Service.Consumers.OrderCreated.OrderCreatedConsumer[0]
      OrderCreatedConsumer Log, Level : Debug, Message : [thrd:main]: Group "orderCreated" changed join state wait-join -> init (v1, state up)
info: Service.Consumers.OrderCreated.OrderCreatedConsumer[0]
      OrderCreatedConsumer Log, Level : Debug, Message : [thrd:main]: Group "orderCreated": join with 1 (1) subscribed topic(s)
info: Service.Consumers.OrderCreated.OrderCreatedConsumer[0]
      OrderCreatedConsumer Log, Level : Debug, Message : [thrd:main]: consumer join: metadata for subscription is up to date (50ms old)
info: Service.Consumers.OrderCreated.OrderCreatedConsumer[0]
      OrderCreatedConsumer Log, Level : Debug, Message : [thrd:main]: OUR_BOOTSTRAP_SERVERS/2: Joining group "orderCreated" with 1 subscribed topic(s)
info: Service.Consumers.OrderCreated.OrderCreatedConsumer[0]
      OrderCreatedConsumer Log, Level : Debug, Message : [thrd:main]: Group "orderCreated" changed join state init -> wait-join (v1, state up)
info: Service.Consumers.OrderCreated.OrderCreatedConsumer[0]
      OrderCreatedConsumer Log, Level : Debug, Message : [thrd:GroupCoordinator]: GroupCoordinator/2: Sent JoinGroupRequest (v5, 214 bytes @ 0, CorrId 5)
info: Service.Consumers.OrderCreated.OrderCreatedConsumer[0]
      OrderCreatedConsumer Log, Level : Debug, Message : [thrd:GroupCoordinator]: Broadcasting state change
info: Service.Consumers.OrderCreated.OrderCreatedConsumer[0]
      OrderCreatedConsumer Log, Level : Debug, Message : [thrd:GroupCoordinator]: GroupCoordinator/2: Received JoinGroupResponse (v5, 113 bytes, CorrId 5, rtt 3250.76ms)
info: Service.Consumers.OrderCreated.OrderCreatedConsumer[0]
      OrderCreatedConsumer Log, Level : Debug, Message : [thrd:main]: JoinGroup response: GenerationId 968, Protocol range, LeaderId rdkafka-ded02292-edfd-432f-ae84-573714df9d0b, my MemberId rdkafka-c6180872-7e7f-4f7a-a470-fa51bd6beab4, 0 members in group: (no error)
info: Service.Consumers.OrderCreated.OrderCreatedConsumer[0]
      OrderCreatedConsumer Log, Level : Debug, Message : [thrd:main]: Group "orderCreated" changed join state wait-join -> wait-sync (v1, state up)
info: Service.Consumers.OrderCreated.OrderCreatedConsumer[0]
      OrderCreatedConsumer Log, Level : Debug, Message : [thrd:GroupCoordinator]: GroupCoordinator/2: Sent SyncGroupRequest (v3, 97 bytes @ 0, CorrId 6)
info: Service.Consumers.OrderCreated.OrderCreatedConsumer[0]
      OrderCreatedConsumer Log, Level : Debug, Message : [thrd:GroupCoordinator]: Broadcasting state change
info: Service.Consumers.OrderCreated.OrderCreatedConsumer[0]
      OrderCreatedConsumer Log, Level : Debug, Message : [thrd:GroupCoordinator]: GroupCoordinator/2: Received SyncGroupResponse (v3, 64 bytes, CorrId 6, rtt 79.98ms)
info: Service.Consumers.OrderCreated.OrderCreatedConsumer[0]
      OrderCreatedConsumer Log, Level : Debug, Message : [thrd:main]: SyncGroup response: Success (54 bytes of MemberState data)
info: Service.Consumers.OrderCreated.OrderCreatedConsumer[0]
      OrderCreatedConsumer Log, Level : Debug, Message : [thrd:main]: Group "orderCreated": new assignment of 3 partition(s) in join state wait-sync
```

How to reproduce
================
Start consuming messages from a topic and commit message, the error occurs in first commit.

Checklist
=========

Please provide the following information:
 - [x] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [x] Confluent.Kafka nuget version 1.5.0.
 - [x] Apache Kafka version 2.2.0.
 - [x] Client configuration is provided above.
 - [x] Operating system is Linux.
 - [x] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
this would be due to timing of a group rebalance (we could look at the sequence of events in the debug logs to see precisely what's going on). but a better pattern is to use StoreOffsets and set EnableAutoOffsetCommit = true / EnableAutoOffsetStore = false, and let the consumer take care committing offsets, which it will do appropriately in the event of a rebalance. i should update the examples

**Comment by dogac00** [comment]
Thanks for the response @mhowlett, that explains why we get this commit error just in consumer startup. We did not have time for changing our commit pattern. But I was able to solve this issue with increasing my session timeout and my heartbeat interval, with `SessionTimeoutMs = 30000` and `HeartbeatIntervalMs = 10000`. I hope this helps for anyone coming across this issue in future.
