### ISSUE TITLE
unable to load librdkafka when call from window

### ISSUE THREAD

**Issue by RammG** [confluentinc/confluent-kafka-dotnet#153]
Here is the message I got:
   at Confluent.Kafka.Impl.LibRdKafka.conf_new()
   at Confluent.Kafka.Impl.SafeConfigHandle.Create()
   at Confluent.Kafka.Producer..ctor(IEnumerable`1 config, Boolean manualPoll, Boolean disableDeliveryReports)
   at Confluent.Kafka.Producer`2..ctor(IEnumerable`1 config, ISerializer`1 keySerializer, ISerializer`1 valueSerializer, Boolean manualPoll, Boolean disableDeliveryReports)
   at Confluent.Kafka.Producer`2..ctor(IEnumerable`1 config, ISerializer`1 keySerializer, ISerializer`1 valueSerializer)
   at ThomsonReuters.Metadata.BLL.RDFServiceHelper.SendKafkaTopic(Nullable`1 serviceId, List`1 queueObjectList) in C:\TR\metadata\branch\ThomsonReuters.MetadataManagement\ThomsonReuters.Metadata.BLL\RDFServiceHelper.cs:line 211
   at ThomsonReuters.Metadata.BLL.RDFServiceHelper.HandleRDFSyncRequest(Nullable`1 serviceId, List`1 queueObjectList) in C:\TR\metadata\branch\ThomsonReuters.MetadataManagement\ThomsonReuters.Metadata.BLL\RDFServiceHelper.cs:line 201
   at ThomsonReuters.Metadata.BLL.RDFServiceHelper.<>c__DisplayClass8_1.<GetRecordsFromQueue>b__3(Object arg) in C:\TR\metadata\branch\ThomsonReuters.MetadataManagement\ThomsonReuters.Metadata.BLL\RDFServiceHelper.cs:line 191
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

And I can find librdkafka.dll in my local, I downloaded package for both confluent.kafka and librdkafka.dist. anything missing here?

**Comment by mhowlett** [comment]
Are you seeing `System.DllNotFoundException: Unable to load DLL 'librdkafka': The specified module could not be found. ` (what's the exception)?

It does look like it's unable to find the native librdkafka dll for some reason.

**Comment by RammG** [comment]
I did install package from NuGet for Confluent.kafka and librdkafka.redist, is there any default path I should put librdkafka.dll in?

**Comment by mhowlett** [comment]
Try referencing version 0.9.5 of Confluent.Kafka which was just released. It has some packaging related fixes. 
If that does not work, try putting librdkafka.dll in the same directory as Confluent.Kafka.dll.

If 0.9.5 does not work for you, some more information about your application / environment would be good to know.

**Comment by RammG** [comment]
yes, it is fixed with new 0.9.5 build, thanks.
