### ISSUE TITLE
Protobuf message from confluent-kafka-dotnet causing Illegal Capacity: -1 in kafka connector

### ISSUE THREAD

**Issue by plachta11b** [confluentinc/confluent-kafka-dotnet#1542]
I have difficulty to send protobuf messages from .net client into kafka connector. Can I use kafka-dotnet this way? I [read](https://riferrei.com/2020/07/09/data-sharing-between-java-go-using-kafka-and-protobuf/) that there are some issues with compatibility between different lang implementations. Is this my problem? Any hint appreciated :)

```stacktrace
[2021-02-25 17:19:07,058] ERROR WorkerSinkTask{id=demo-redis-sink-connector-pb-2} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask)
org.apache.kafka.connect.errors.ConnectException: Tolerance exceeded in error handler
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:206)
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execute(RetryWithToleranceOperator.java:132)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.convertAndTransformRecord(WorkerSinkTask.java:501)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.convertMessages(WorkerSinkTask.java:478)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:328)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:232)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:201)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:185)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:234)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.apache.kafka.connect.errors.DataException: Failed to deserialize data for topic protobuffer.test to Protobuf: 
	at io.confluent.connect.protobuf.ProtobufConverter.toConnectData(ProtobufConverter.java:131)
	at org.apache.kafka.connect.storage.Converter.toConnectData(Converter.java:87)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.convertValue(WorkerSinkTask.java:545)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.lambda$convertAndTransformRecord$1(WorkerSinkTask.java:501)
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndRetry(RetryWithToleranceOperator.java:156)
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:190)
	... 13 more
Caused by: org.apache.kafka.common.errors.SerializationException: Error deserializing Protobuf message for id 6
Caused by: java.lang.IllegalArgumentException: Illegal Capacity: -1
	at java.base/java.util.ArrayList.<init>(ArrayList.java:158)
	at io.confluent.kafka.schemaregistry.protobuf.MessageIndexes.readFrom(MessageIndexes.java:73)
	at io.confluent.kafka.serializers.protobuf.AbstractKafkaProtobufDeserializer.deserialize(AbstractKafkaProtobufDeserializer.java:121)
	at io.confluent.kafka.serializers.protobuf.AbstractKafkaProtobufDeserializer.deserializeWithSchemaAndVersion(AbstractKafkaProtobufDeserializer.java:242)
	at io.confluent.connect.protobuf.ProtobufConverter$Deserializer.deserialize(ProtobufConverter.java:176)
	at io.confluent.connect.protobuf.ProtobufConverter.toConnectData(ProtobufConverter.java:114)
	at org.apache.kafka.connect.storage.Converter.toConnectData(Converter.java:87)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.convertValue(WorkerSinkTask.java:545)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.lambda$convertAndTransformRecord$1(WorkerSinkTask.java:501)
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndRetry(RetryWithToleranceOperator.java:156)
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:190)
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execute(RetryWithToleranceOperator.java:132)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.convertAndTransformRecord(WorkerSinkTask.java:501)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.convertMessages(WorkerSinkTask.java:478)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:328)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:232)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:201)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:185)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:234)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

How to reproduce
================
I am not sure if connector configuration is needed.

Connector image: `confluentinc/cp-kafka-connect-base:6.1.0`
Dev image: `mcr.microsoft.com/vscode/devcontainers/dotnetcore:0-3.1`

```csproj
<PackageReference Include="Confluent.Kafka" Version="1.6.2" />
<PackageReference Include="Confluent.SchemaRegistry" Version="1.6.2" />
<PackageReference Include="Confluent.SchemaRegistry.Serdes.Protobuf" Version="1.6.2" />
<PackageReference Include="Google.Protobuf" Version="3.15.2" />
```
Slightly updated protobuf [example](https://github.com/confluentinc/confluent-kafka-dotnet/blob/master/examples/Protobuf/Program.cs).
```c#
static async System.Threading.Tasks.Task Main(string[] args)
{
	var producerConfig = new ProducerConfig { BootstrapServers = "ip1:9094,ip2:9094", QueueBufferingMaxMessages = 1000000 };
	var schemaRegistryConfig = new SchemaRegistryConfig
	{
		Url = "http://host.docker.internal:8081",
	};
	string topicName = "protobuffer.test";
	using (var schemaRegistry = new CachedSchemaRegistryClient(schemaRegistryConfig))
	using (var producer =
		new ProducerBuilder<string, MyNamespace.Protos.Message.SimpleMessage>(producerConfig)
			.SetValueSerializer(new ProtobufSerializer<MyNamespace.Protos.Message.SimpleMessage>(schemaRegistry))
			.Build())
	{
		string id;
		while ((id = Console.ReadLine()) != "q")
		{
			MyNamespace.Protos.Message.SimpleMessage data = new MyNamespace.Protos.Message.SimpleMessage { MyContent = id };
			await producer
				.ProduceAsync(topicName, new Message<string, MyNamespace.Protos.Message.SimpleMessage> { Key = id, Value = data })
				.ContinueWith(task => Console.WriteLine(task.IsFaulted
					? $"error producing message: {task.Exception.Message}"
					: $"produced to: {task.Result.TopicPartitionOffset}"));
		}
	}
}
```

Using redis connector https://github.com/jaredpetersen/kafka-connect-redis configured as below:
```
curl --request POST \
    --url "localhost:$KCR_PORT/connectors" \
    --header 'content-type: application/json' \
    --data '{
        "name": "demo-redis-sink-connector-pb",
        "config": {
            "connector.class": "io.github.jaredpetersen.kafkaconnectredis.sink.RedisSinkConnector",
            "key.converter": "org.apache.kafka.connect.storage.StringConverter",
            "key.converter.key.subject.name.strategy": "io.confluent.kafka.serializers.subject.TopicRecordNameStrategy",
            "value.converter": "io.confluent.connect.protobuf.ProtobufConverter",
            "value.converter.schema.registry.url": "http://kafka-schema-registry:8081",
            "value.converter.value.subject.name.strategy": "io.confluent.kafka.serializers.subject.TopicRecordNameStrategy",
            "tasks.max": "3",
            "topics": "protobuffer.test",
            "redis.uri": "redis://REDACTED@redis-v1-redis-cluster.redis:6379",
            "redis.cluster.enabled": true
        }
    }'
```

**Comment by mhowlett** [comment]
did you figure it out?

i will need to dig in a bit to make progress here. It looks like the connector has schema registry integration, and so this should work seamlessly with the .net client.

does SimpleMessage reference any other proto file? there is some complexity here in the implementation, have you tried a protofile as trivial as having just one message with a single int property?

**Comment by plachta11b** [comment]
I was not able to make it work so I throw away connector and removed this demo. SimpleMessage was .proto file containing only one string and later maybe timestamp, but nothing complex. If I get access to new cluster I will try int instead of string.

**Comment by ginwakeup** [comment]
Did you solve this? I am experiencing the same with a simple protobuf published in Python.
The KafkaConnector breaks with the same error:
```
1363: Failed to deserialize data for topic jobs to Protobuf:  (org.apache.kafka.connect.runtime.WorkerSinkTask)
org.apache.kafka.connect.errors.DataException: Failed to deserialize data for topic jobs to Protobuf:
        at io.confluent.connect.protobuf.ProtobufConverter.toConnectData(ProtobufConverter.java:130)
        at org.apache.kafka.connect.storage.Converter.toConnectData(Converter.java:87)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.convertValue(WorkerSinkTask.java:540)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.lambda$convertAndTransformRecord$2(WorkerSinkTask.java:496)
        at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndRetry(RetryWithToleranceOperator.java:156)
        at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:190)
        at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execute(RetryWithToleranceOperator.java:132)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.convertAndTransformRecord(WorkerSinkTask.java:496)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.convertMessages(WorkerSinkTask.java:473)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:328)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:232)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:201)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:182)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:231)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.apache.kafka.common.errors.SerializationException: Error deserializing Protobuf message for id 3
Caused by: java.lang.IllegalArgumentException: Illegal Capacity: -1
        at java.base/java.util.ArrayList.<init>(ArrayList.java:158)
        at io.confluent.kafka.schemaregistry.protobuf.MessageIndexes.readFrom(MessageIndexes.java:73)
        at io.confluent.kafka.serializers.protobuf.AbstractKafkaProtobufDeserializer.deserialize(AbstractKafkaProtobufDeserializer.java:121)
        at io.confluent.kafka.serializers.protobuf.AbstractKafkaProtobufDeserializer.deserializeWithSchemaAndVersion(AbstractKafkaProtobufDeserializer.java:242)
        at io.confluent.connect.protobuf.ProtobufConverter$Deserializer.deserialize(ProtobufConverter.java:174)
        at io.confluent.connect.protobuf.ProtobufConverter.toConnectData(ProtobufConverter.java:113)
        at org.apache.kafka.connect.storage.Converter.toConnectData(Converter.java:87)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.convertValue(WorkerSinkTask.java:540)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.lambda$convertAndTransformRecord$2(WorkerSinkTask.java:496)
        at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndRetry(RetryWithToleranceOperator.java:156)
        at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:190)
        at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execute(RetryWithToleranceOperator.java:132)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.convertAndTransformRecord(WorkerSinkTask.java:496)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.convertMessages(WorkerSinkTask.java:473)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:328)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:232)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:201)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:182)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:231)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)

```

**Comment by plachta11b** [comment]
@ginwakeup No, I was not able to look into this issue again.

**Comment by ginwakeup** [comment]
> 
> 
> @ginwakeup No, I was not able to look into this issue again.

Any chance this could be looked into it? It's quite blocking in our Connectors pipeline.

**Comment by mhowlett** [comment]
try master branch

https://github.com/confluentinc/confluent-kafka-dotnet/commit/5331f7af6063efcebbc3b830c59ded8f22ceb611

**Comment by mhowlett** [comment]
(the format for the protobuf metadata serialization changed early on, that PR includes changes to address this).

**Comment by ginwakeup** [comment]
Hey @mhowlett , I am not using confluent-kafka for NET but confluent-kafka for python, do you have a branch for it that I can test as well?

Thanks.

**Comment by mhowlett** [comment]
it might be worth trying master branch, though after a quick look through the corresponding SR change that was merged I didn't see anything related to this issues. if that doesn't work, feel free to open an issue on the python repo linking to this thread.

**Comment by anchitj** [comment]
@plachta11b Is this still an issue?

**Comment by plachta11b** [comment]
I end up writing an app to workaround this. I was not able to revisit this since then. I would close this issue.
