### ISSUE TITLE
[Question] How receive data from kafka from specific date

### ISSUE THREAD

**Issue by sergius1che** [confluentinc/confluent-kafka-dotnet#1546]
[Stackowerflow issue](https://stackoverflow.com/questions/65781243/how-receive-data-from-kafka-from-specific-date)
I want to subscribe to topic and receive data from specific date. The method call throws exception:
>Confluent.Kafka.KafkaException: Local: Erroneous state

My code (net5.0):
```csharp
var adminClient = new AdminClientBuilder(_kafkaConfig.AsEnumerable())
    .SetLogHandler((c, l) => Console.WriteLine($"Admin log: " + l.Message))
    .SetErrorHandler((c, l) => Console.WriteLine($"Admin error: " + l.Reason))
    .Build();
var topicMetadata = adminClient.GetMetadata(_config.Topic, TimeSpan.FromSeconds(2));
var partitions = topicMetadata
    .Topics
    .First(x => x.Topic == _config.Topic)
    .Partitions;
var partitionsOffsets = partitions
    .Select(x => new TopicPartitionTimestamp(_config.Topic, x.PartitionId, new Timestamp(_config.OffsetDateUtc)));

consumer = CreateConsumer();

foreach (var p in partitions)
{
    consumer.Assign(new TopicPartition(_config.Topic, p.PartitionId));
}

var offsets = consumer.OffsetsForTimes(partitionsOffsets, TimeSpan.FromSeconds(2));

//await Task.Delay(1000);

foreach (var o in offsets)
{
    consumer.Seek(o);
}
```
If I add awaiting: `await Task.Delay(1000);`. Method `Seek()` doesn't throw exception. How I set offset by date, without `Task.Delay`?

I use:
- Confluent.Kafka nuget version: 1.5.3
- Confluent Platform: 5.5.1
- OS: Linux

Full logs:
```
Admin log: [thrd:app]: Configuration property group.id is a consumer property and will be ignored by this producer instance

Error: Confluent.Kafka.KafkaException: Local: Erroneous state
   at Confluent.Kafka.Impl.SafeKafkaHandle.Seek(String topic, Partition partition, Offset offset, Int32 millisecondsTimeout)
   at Confluent.Kafka.Consumer`2.Seek(TopicPartitionOffset tpo)
   at KafkaSearch.Program.Main(String[] args) in D:\Repository\KafkaSearcher\kafkasercher\src\KafkaSearch\Program.cs:line 62
```

**Comment by sergius1che** [comment]
I found! 
Next code work korrect:

```csharp
var adminClient = new AdminClientBuilder(_kafkaConfig.AsEnumerable())
    .SetLogHandler((c, l) => Console.WriteLine($"Admin log: " + l.Message))
    .SetErrorHandler((c, l) => Console.WriteLine($"Admin error: " + l.Reason))
    .Build();
var topicMetadata = adminClient.GetMetadata(_config.Topic, TimeSpan.FromSeconds(2));
var partitions = topicMetadata
    .Topics
    .First(x => x.Topic == _config.Topic)
    .Partitions;
var partitionsOffsets = partitions
    .Select(x => new TopicPartitionTimestamp(_config.Topic, x.PartitionId, new Timestamp(_config.OffsetDateUtc)));

consumer = CreateConsumer();

//Remove 
//foreach (var p in partitions)
//{
//    consumer.Assign(new TopicPartition(_config.Topic, p.PartitionId));
//}

var offsets = consumer.OffsetsForTimes(partitionsOffsets, TimeSpan.FromSeconds(2));

//await Task.Delay(1000);

foreach (var o in offsets)
{
    consumer.Assign(o);
}
```
