### ISSUE TITLE
[Producer] After TopicAuthorizationFailed error that producer instance times out permanently 

### ISSUE THREAD

**Issue by saherahwal** [confluentinc/confluent-kafka-dotnet#1551]
Description
===========
We are seeing an issue where the singleton producer after receiving TopicAuthorizationFailed , now always timing out and never able to publish a message.

NOTE: we are using Kerberos to authenticate and authorize producer/consumer requests against brokers. It's on Linux (.net core application) with Service Principal name provided and client keytab file.

This is the original message received days ago
```
Confluent.Kafka.ProduceException`2[System.String,sample_app.Sample]: Broker: Topic authorization failed
   at Confluent.Kafka.Producer`2.ProduceAsync(TopicPartition topicPartition, Message`2 message, CancellationToken cancellationToken)
   at Kafka.Producer.EventBusProducer`2.<>c__DisplayClass13_0.<<ProduceAsync>b__0>d.MoveNext()

```

We see some logs in vicinity indicating Kerberos ticket refresh failed:

```
[thrd:main]: Kerberos ticket refresh failed: kinit -R -t "/opt/messaging/client.keytab" -k user@domain.corp|| kinit -t "/opt/messaging/client.keytab" -k user@domain.corp : exited with code 1
```

Now however, other producer instances are working just fine and producing messages successfully against other topics and the same topics of the producer in question.

However, that same producer is timing out and never recovering. We know for sure a restart will recover the producer but we want to understand and get to the bottom of this without losing the repro.

This is the new error message we keep getting every time we try to publish using that particular producer instance.
```
Confluent.Kafka.ProduceException`2[System.String,sample_app.Sample]: Local: Message timed out
   at Confluent.Kafka.Producer`2.ProduceAsync(TopicPartition topicPartition, Message`2 message, CancellationToken cancellationToken)
   at Kafka.Producer.EventBusProducer`2.<>c__DisplayClass13_0.<<ProduceAsync>b__0>d.MoveNext()
```
and does not seem to be recovering at all.

How to reproduce
================
We are not able to reproduce this on-demand. We have a node with live repro currently that is stuck with timeout errors constantly.

Can you please provide suggestions on how to debug further and proceed with this investigation? 

The Kafka brokers do not seem to be showing any error logs. In fact we see log statements indicating the user principal authenticated successfully. 

```
Successfully authenticated client: authenticationID=user@ourdomain; authorizationID=user@ourdomain. (org.apache.kafka.common.security.authenticator.SaslServerCallbackHandler)```

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [x ] Confluent.Kafka nuget version.  (Confluent.Kafka 1.5.0)
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [x ] Operating system.  (Linux)
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ x ] Critical issue.

**Comment by saherahwal** [comment]
we found that chef policy was externally changing the Kerberos ticket and logging in as different user. The details are irrelevant but intermittingly when that external script ran, our service became running as different user and hence rejected from producing to topics that user has no access to write to.
