### ISSUE TITLE
Schema not found; error code: 40403

### ISSUE THREAD

**Issue by vivekkwatra** [confluentinc/confluent-kafka-dotnet#1574]
Description
===========
I'm trying to produce a JSON message using JSON Serializer(below snippet for your reference) however I'm unable to produce and get the error while calling produce() method:

_var _producer = new ProducerBuilder<string, Object>(_producerConfig)
                   .SetKeySerializer(Confluent.Kafka.Serializers.Utf8)
                   .SetValueSerializer(new JsonSerializer<Object>(schemaRegistry, jsonSerializerConfig).AsSyncOverAsync())
                   .SetErrorHandler((_, e) => Console.WriteLine($"Error: {e.Reason}"))
                   .Build();_
_producer .Produce(topic, new Message<string, Object> {............................................................});

One or more errors occurred. (Confluent.SchemaRegistry.SchemaRegistryException: **Schema not found; error code: 40403**
   at Confluent.SchemaRegistry.RestService.ExecuteOnOneInstanceAsync(Func`1 createRequest)
   at Confluent.SchemaRegistry.RestService.RequestAsync[T](String endPoint, HttpMethod method, Object[] jsonBody)
   at Confluent.SchemaRegistry.RestService.LookupSchemaAsync(String subject, Schema schema, Boolean ignoreDeletedSchemas)
   at Confluent.SchemaRegistry.CachedSchemaRegistryClient.GetSchemaIdAsync(String subject, Schema schema)
   at Confluent.SchemaRegistry.Serdes.JsonSerializer`1.SerializeAsync(T value, SerializationContext context)
   at Confluent.Kafka.SyncOverAsync.SyncOverAsyncSerializer`1.Serialize(T data, SerializationContext context)
   at Confluent.Kafka.Producer`2.Produce(TopicPartition topicPartition, Message`2 message, Action`1 deliveryHandler))

Please let me know what I might be missing.

How to reproduce
================

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ ] Confluent.Kafka nuget version. 1.6.3
 - [ ] Apache Kafka version. 
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
are you able to successfully run the example?

https://github.com/confluentinc/confluent-kafka-dotnet/blob/master/examples/JsonSerialization/Program.cs

**Comment by vivekkwatra** [comment]
Yes I am able to run the example successfully. It seems to issue with passing Object as value for producerbuilder. And the JSONSerializer is unable to find its relevant schema.

**Comment by vivekkwatra** [comment]
Do you have any example where I can convert JSON string into Generic Record in c#? Similar to what provided in Java https://github.com/allegro/json-avro-converter/blob/master/converter/src/main/java/tech/allegro/schema/json2avro/converter/JsonAvroConverter.java

**Comment by sunnybenari** [comment]
Hey @vivekkwatra ,
I encountered a similar issue in the past. 
You get this schema exception `Error code 40403 – Schema not found` when your schema is not registered

https://docs.confluent.io/platform/current/schema-registry/develop/api.html#schemas
