### ISSUE TITLE
No such configuration property: "client.software.name" 

### ISSUE THREAD

**Issue by shinshinshin3** [confluentinc/confluent-kafka-dotnet#1591]
Description
===========
I found the same exception occurred as # 1417. And I use Confluent.Kafka 1.5.2.

Exception : Message:No such configuration property: "client.software.name" 
StackTrace: at Confluent.Kafka.Impl.SafeConfigHandle.Set(String name, String value)
at Confluent.Kafka.Producer`2.<>c__DisplayClass54_0.<.ctor>b__5(KeyValuePair`2 kvp)
at System.Collections.Generic.List`1.ForEach(Action`1 action)
at Confluent.Kafka.Producer`2..ctor(ProducerBuilder`2 builder)
at Confluent.Kafka.ProducerBuilder`2.Build()

Checklist
=========
Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [* ] Confluent.Kafka nuget version. 1.5.2
 - [* ] Apache Kafka version.　2.4
 - [ ] Client configuration.
 - [Windows ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [* ] Critical issue.

**Comment by mhowlett** [comment]
Confluent.Kafka is loading an old version of librdkafka for some reason. It may be finding it somewhere else on your system rather than using the dependent nuget version (there are some bugs related to this, but i forget on which platform). You need to find the version it's loading and remove it. You can verify this is what is happening by using `Library.VersionString` before any other client call to print the version of the library that is being loaded.

**Comment by anchitj** [comment]
@shinshinshin3 Is this still an issue?
