### ISSUE TITLE
Cancelling a client throws "application *assign() call failed"

### ISSUE THREAD

**Issue by WinniX** [confluentinc/confluent-kafka-dotnet#1624]
Description
===========
Hello team!
I am investigating the "ExactlyOnce" example. When I have 2 map clients running - everything is working as expected, until I cancel any of my clients by pressing "CTRL+C". As a result I see this:
```
Exiting MapWords consume loop due to an exception: System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Confluent.Kafka.Examples.ExactlyOnce.Program.Processor_MapWords(String brokerList, String clientId, CancellationToken ct) in C:\Users\elaha\src\local\ExactlyOnce\Program.cs:line 371
** MapWords consumer group partitions revoked: [6,7,8,9,10,11], remaining: []
%4|1621625706.762|ASSIGN|map_client_id_1_consumer#consumer-3| [thrd:main]: Group "map-words-consumer-group": application *assign() call failed: Changes to the current assignment must be made using incremental_assign() or incremental_unassign() when rebalance protocol type is COOPERATIVE
```
After this the cancelled process is hanging and not responding. I was expecting to see some sort of a graceful shutdown.
The second client is picking up the other partitions as expected. So the question is whether this behavior is expected or I am doing something wrong?

Thank you in advance!

How to reproduce
================
1) Get ExactlyOnce example: https://github.com/confluentinc/confluent-kafka-dotnet/tree/master/examples/ExactlyOnce
2) Produce data:
```bash
dotnet run localhost:9092 gen
```
3) Run 2 map clients in parallel:
```bash
dotnet run localhost:9092 map map_client_id_1
```
and 
```bash
dotnet run localhost:9092 map map_client_id_2
```

Checklist
=========

Please provide the following information:
 - [x] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [x] Confluent.Kafka nuget version (1.7.0).
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [x] Operating system Win10.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
this my already be resolved in librdkafka master (i recall a PR that may be related). suggest building a version of librdkafka from master and overwriting the builds supplied by librdkafka.redist and seeing if that resolves the issue.

i'm expecting a release on the timeframe of about a month, if this is still an issue, we need to get it resolved.

**Comment by mhowlett** [comment]
would be good to incorporate this into our chaos testing
