### ISSUE TITLE
Some Protobuf tests are failing

### ISSUE THREAD

**Issue by rayokota** [confluentinc/confluent-kafka-dotnet#1630]
Per @mhowlett , with .net core 2.1 installed, and then running `dotnet test -f netcoreapp2.1`, the following test failures occur:

```[xUnit.net 00:02:58.3318311]     Confluent.SchemaRegistry.Serdes.IntegrationTests.Tests.ProduceConsumeNestedProtobuf(bootstrapServers: "localhost:9092", schemaRegistryServers: "localhost:8081") [FAIL]
  Failed Confluent.SchemaRegistry.Serdes.IntegrationTests.Tests.ProduceConsumeNestedProtobuf(bootstrapServers: "localhost:9092", schemaRegistryServers: "localhost:8081") [46 s]
  Error Message:
   Assert.Equal() Failure
Expected: 3
Actual:   6
  Stack Trace:
     at Confluent.SchemaRegistry.Serdes.IntegrationTests.Tests.ProduceConsumeNestedProtobuf(String bootstrapServers, String schemaRegistryServers) in /Users/matt/git/confluent-kafka-dotnet/test/Confluent.SchemaRegistry.Serdes.IntegrationTests/Tests_Protobuf/ProduceConsumeNested.cs:line 78
[xUnit.net 00:03:52.0111808]     Confluent.SchemaRegistry.Serdes.IntegrationTests.Tests.ProduceConsumeSchemaManyMessagesProtobuf(bootstrapServers: "localhost:9092", schemaRegistryServers: "localhost:8081") [FAIL]
  Failed Confluent.SchemaRegistry.Serdes.IntegrationTests.Tests.ProduceConsumeSchemaManyMessagesProtobuf(bootstrapServers: "localhost:9092", schemaRegistryServers: "localhost:8081") [46 s]
  Error Message:
   Assert.Equal() Failure
Expected: 1
Actual:   2
  Stack Trace:
     at Confluent.SchemaRegistry.Serdes.IntegrationTests.Tests.ProduceConsumeSchemaManyMessagesProtobuf(String bootstrapServers, String schemaRegistryServers) in /Users/matt/git/confluent-kafka-dotnet/test/Confluent.SchemaRegistry.Serdes.IntegrationTests/Tests_Protobuf/ProduceConsumeSchemaManyMessages.cs:line 77
[xUnit.net 00:05:00.0445875]     Confluent.SchemaRegistry.Serdes.IntegrationTests.Tests.ConsumePartitionEOF(bootstrapServers: "localhost:9092", schemaRegistryServers: "localhost:8081") [FAIL]
  Failed Confluent.SchemaRegistry.Serdes.IntegrationTests.Tests.ConsumePartitionEOF(bootstrapServers: "localhost:9092", schemaRegistryServers: "localhost:8081") [1 s]
  Error Message:
   Assert.NotNull() Failure
  Stack Trace:
     at Confluent.SchemaRegistry.Serdes.IntegrationTests.Tests.ConsumePartitionEOF(String bootstrapServers, String schemaRegistryServers) in /Users/matt/git/confluent-kafka-dotnet/test/Confluent.SchemaRegistry.Serdes.IntegrationTests/Tests_Avro/ConsumePartitionEOF.cs:line 77

Failed!  - Failed:     3, Passed:    23, Skipped:     0, Total:    26, Duration: 4 m 59 s - /Users/matt/git/confluent-kafka-dotnet/test/Confluent.SchemaRegistry.Serdes.IntegrationTests/bin/Debug/netcoreapp2.1/Confluent.SchemaRegistry.Serdes.IntegrationTests.dll (netcoreapp2.1)
```

**Comment by mhowlett** [comment]
Following #1628, there are now only 2 failures:

```
[xUnit.net 00:02:58.3557683]     Confluent.SchemaRegistry.Serdes.IntegrationTests.Tests.ProduceConsumeNestedProtobuf(bootstrapServers: "localhost:9092", schemaRegistryServers: "localhost:8081") [FAIL]
  Failed Confluent.SchemaRegistry.Serdes.IntegrationTests.Tests.ProduceConsumeNestedProtobuf(bootstrapServers: "localhost:9092", schemaRegistryServers: "localhost:8081") [46 s]
  Error Message:
   Assert.Equal() Failure
Expected: 3
Actual:   6
  Stack Trace:
     at Confluent.SchemaRegistry.Serdes.IntegrationTests.Tests.ProduceConsumeNestedProtobuf(String bootstrapServers, String schemaRegistryServers) in /Users/matt/git/confluent-kafka-dotnet/test/Confluent.SchemaRegistry.Serdes.IntegrationTests/Tests_Protobuf/ProduceConsumeNested.cs:line 78
[xUnit.net 00:03:52.0020340]     Confluent.SchemaRegistry.Serdes.IntegrationTests.Tests.ProduceConsumeSchemaManyMessagesProtobuf(bootstrapServers: "localhost:9092", schemaRegistryServers: "localhost:8081") [FAIL]
  Failed Confluent.SchemaRegistry.Serdes.IntegrationTests.Tests.ProduceConsumeSchemaManyMessagesProtobuf(bootstrapServers: "localhost:9092", schemaRegistryServers: "localhost:8081") [46 s]
  Error Message:
   Assert.Equal() Failure
Expected: 1
Actual:   2
  Stack Trace:
     at Confluent.SchemaRegistry.Serdes.IntegrationTests.Tests.ProduceConsumeSchemaManyMessagesProtobuf(String bootstrapServers, String schemaRegistryServers) in /Users/matt/git/confluent-kafka-dotnet/test/Confluent.SchemaRegistry.Serdes.IntegrationTests/Tests_Protobuf/ProduceConsumeSchemaManyMessages.cs:line 77
```

**Comment by mhowlett** [comment]
i can't quickly find the relevant PR, but this is resolved.
