### ISSUE TITLE
Kafka Performance Error

### ISSUE THREAD

**Issue by HarshMultani** [confluentinc/confluent-kafka-dotnet#1634]
Hi @mhowlett 

I want to measure Kafka Performance and so I started zookeeper and kafka and then created topic quickstart-events.

And then when I run the command - 

bin/kafka-producer-perf-test.sh --topic quickstart-events --num-records 500 --throughput -1 --producer-props bootstrap.servers=localhost:9092 batch.size=1000 acks=1 linger.ms=100000 buffer.memory=4294967296 compression.type=text request.timeout.ms=300000 --record-size 1000

I get the error - 
Exception in thread "main" org.apache.kafka.common.KafkaException: Failed to construct kafka producer
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:441)
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:302)
	at org.apache.kafka.tools.ProducerPerformance.main(ProducerPerformance.java:108)
Caused by: java.lang.IllegalArgumentException: Unknown compression name: text
	at org.apache.kafka.common.record.CompressionType.forName(CompressionType.java:198)
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:395)

Does anyone know why is it occuring and how can it be resolved?
Thanks

**Comment by mhowlett** [comment]
`Caused by: java.lang.IllegalArgumentException: Unknown compression name: text` 

valid values for `compression.type` are `gzip`, `snappy`, `lz4` and `zstd`

**Comment by HarshMultani** [comment]
Thanks for this @mhowlett.
It worked.

I need one more suggestion - 

When I am testing kafka consumer using local kafka, it works fine.

bin/kafka-consumer-perf-test.sh --topic quickstart-events --bootstrap-server localhost:9092 --messages 1000

start.time, end.time, data.consumed.in.MB, MB.sec, data.consumed.in.nMsg, nMsg.sec, rebalance.time.ms, fetch.time.ms, fetch.MB.sec, fetch.nMsg.sec

2021-06-18 09:38:24:769, 2021-06-18 09:38:25:401, 0.9527, 1.5075, 1000, 1582.2785, 1623989305231, -1623989304599, -0.0000, -0.0000

But, when I am trying to test kafka in server, it is not consuming at all.

Even for 1 message it is not able to consume.

bin/kafka-consumer-perf-test.sh --topic connection --bootstrap-server kafka.dev.net:9092 --messages 1 --timeout 100000

start.time, end.time, data.consumed.in.MB, MB.sec, data.consumed.in.nMsg, nMsg.sec, rebalance.time.ms, fetch.time.ms, fetch.MB.sec, fetch.nMsg.sec

WARNING: Exiting before consuming the expected number of messages: timeout (100000 ms) exceeded. You can use the --timeout option to increase the timeout.

2021-06-18 09:51:27:754, 2021-06-18 09:53:07:913, 0.0000, 0.0000, 0, 0.0000, 1623990095140, -1623989994981, -0.0000, -0.0000

What can be the reason?
Thanks..
