### ISSUE TITLE
Doesn't find librdkafka.dll with Costura temp path

### ISSUE THREAD

**Issue by rios0rios0** [confluentinc/confluent-kafka-dotnet#1660]
Description
===========
Hello guys. I'm using [Costura.Fody](https://github.com/Fody/Costura), to embedded all my DLLs inside my .exe final file.
I know that `Confluent.Kafka` (1.7.0) (with Windows 10 x64) needs the `librdkafka.dll`. And, I'm prepared to handle this via `Costura.Fody`.
By design, always my `.exe` tries to load some dependency, `Costura` gives to it the correct path to load the extracted DLLs files.
For example, when my `.exe` needs of the `SomeNativeDll.dll` and try to load with `Assembly.Load`, the path of libraries changed by `Costura` is: "C:\Users\*my.user*\AppData\Local\Temp\Costura\*some.hash*\*system.arch*\SomeNativeDll.dll".

But by design, the `Confluent.Kafka` tries to load `librdkafka.dll` in a manual way, I think.
If we look inside this reference bellow, we can see what I'm saying.
https://github.com/confluentinc/confluent-kafka-dotnet/blob/348c4e34bb996ea0d49e6de71445a28181ccfcfc/src/Confluent.Kafka/Impl/LibRdKafka.cs#L436

I created an workaround (working successfully) with this idea: https://stackoverflow.com/a/66970630/10746857, before call any method inside `Confluent.Kafka`. But I would like to handle this problem, like in the others many libraries that support the way that `Costura` have been implemented. Could you help me to solve my doubt?

I'll send this issue to `Costura` staff, to see what they can say to me too.
The `PreLoadOrder` (https://github.com/Fody/Costura#native-libraries-and-preloadorder) can't fix the unexpected behavior either.
I tried to use this, in hope that `Confluent.Kafka` recognizes that the library have been loaded. But it didn't work.

How to reproduce
================

1. Create any app with .NET 4.7;
2. Add `Confluent.Kafka`;
3. Add `Costura.Fody`;
4. Edit the `FodyWeavears.xml` to:
```
<Weavers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="FodyWeavers.xsd">
  <Costura>
    <Unmanaged32Assemblies>
      librdkafka
      librdkafkacpp
      libzstd
      msvcp120
      msvcr120
      zlib
    </Unmanaged32Assemblies>
    <Unmanaged64Assemblies>
      librdkafka
      librdkafkacpp
      libzstd
      msvcp120
      msvcr120
      zlib
    </Unmanaged64Assemblies>
  </Costura>
</Weavers>
```
5. Add any library you want, to prove that `Costura` works;
6. Call any method of `Confluent.Kafka`;
7. Run, and get you error:
```
Unhandled Exception: System.InvalidOperationException: Error while loading librdkafka.dll or its dependencies from *current.dir*\librdkafka.dll. Check the directory exists, if not check your deployment process. You can also load the library and its dependencies by yourself before any call to Confluent.Kafka ---> System.ComponentModel.Win32Exception: The specified module could not be found
   --- End of inner exception stack trace ---
   at Confluent.Kafka.Impl.Librdkafka.LoadNetFrameworkDelegates(String userSpecifiedPath)
   at Confluent.Kafka.Impl.Librdkafka.Initialize(String userSpecifiedPath)
   at Confluent.Kafka.Producer`2..ctor(ProducerBuilder`2 builder)
   at Confluent.Kafka.ProducerBuilder`2.Build()
   at ActiveDirectory.Infrastructure.Helpers.QueueHelper.<SendMessage>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

The unique piece of code I'm trying to use:
```
var producer = new ProducerBuilder<Null, string>(new ProducerConfig
      {
        ClientId = Dns.GetHostName(),
        BootstrapServers = QueueAddressesList
      }).Build();
      await producer.ProduceAsync(topic, new Message<Null, string> {Value = message});
```

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [x] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [x] Client configuration.
 - [x] Operating system.
 - [x] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by rios0rios0** [comment]
Reference: https://github.com/Fody/Costura/issues/726
