### ISSUE TITLE
Consume Kafka avro:  Local: Key deserialization error

### ISSUE THREAD

**Issue by aureliosaraiva** [confluentinc/confluent-kafka-dotnet#1733]
Description
===========

Guys, I'm taking some errors when trying to consume kafka message in avro pattern. This is the code I'm trying, it's very simple but I didn't find the problem.

I use this same topic, schema avro in Kotlin and Python and I can consume it normally, but in .Net I still can't.

I followed the example in the project repository itself, just making a few simple changes.

How to reproduce
================

```dotnet
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using Confluent.Kafka.SyncOverAsync;
using Confluent.SchemaRegistry;
using Confluent.SchemaRegistry.Serdes;


namespace Confluent.Kafka.Examples.AvroSpecific
{
    class Program
    {

        static async Task Main(string[] args)
        {
            var topics = new List<string>() {
                "xxx"
            };
            Console.WriteLine("Main");

            KafkaConsume(topics);
        }

        static void KafkaConsume(List<string> topics)
        {
      
            var schemaRegistryConfig = new SchemaRegistryConfig
            {
                Url = "xxxx",
                BasicAuthCredentialsSource = AuthCredentialsSource.UserInfo,
                BasicAuthUserInfo = $"xxxx:xxxx",
                RequestTimeoutMs = 9999999
                
            };

            var consumerConfig = new ConsumerConfig {
                BootstrapServers = "xxxx",
                SecurityProtocol = SecurityProtocol.SaslSsl,
                SaslMechanism = SaslMechanism.Plain,
                SaslUsername = "xxx",
                SaslPassword = "xxx"
            };
            consumerConfig.GroupId = "xxx";
            consumerConfig.AutoOffsetReset = AutoOffsetReset.Latest;
            consumerConfig.EnableAutoCommit = false;

            var avroSerializerConfig = new AvroSerializerConfig
            {
                // optional Avro serializer properties:
                BufferBytes = 100
            };

            CancellationTokenSource cts = new CancellationTokenSource();

            using (var schemaRegistry = new CachedSchemaRegistryClient(schemaRegistryConfig))
            using (var consumer =
                new ConsumerBuilder<string, event_tracked_v1>(consumerConfig)
                    .SetKeyDeserializer(new AvroDeserializer<string>(schemaRegistry).AsSyncOverAsync())
                    .SetValueDeserializer(new AvroDeserializer<event_tracked_v1>(schemaRegistry).AsSyncOverAsync())
                    .SetErrorHandler((_, e) => Console.WriteLine($"Error: {e.Reason}"))
                    .Build())
            {
                consumer.Subscribe(topics);

                try
                {
                    while (true)
                    {
                        try
                        {
                            Console.WriteLine(cts.Token);
                            var consumeResult = consumer.Consume();
                            Console.WriteLine($"user name: {consumeResult.Message.Key}, favorite color: {consumeResult.Message.Value.payload.event_name}");
                        }
                        catch (ConsumeException e)
                        {
                            Console.WriteLine(e);
                            Console.WriteLine($"Consume error: {e.Error.Reason}");
                        }
                    }
                }
                catch (OperationCanceledException)
                {
                    consumer.Close();
                }
            }
        }
    }
}
```

```
Main
Confluent.Kafka.ConsumeException: Local: Key deserialization error
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Confluent.SchemaRegistry.Serdes.SpecificDeserializerImpl`1.Deserialize(String topic, Byte[] array)
   at Confluent.SchemaRegistry.Serdes.AvroDeserializer`1.DeserializeAsync(ReadOnlyMemory`1 data, Boolean isNull, SerializationContext context)
   at Confluent.Kafka.SyncOverAsync.SyncOverAsyncDeserializer`1.Deserialize(ReadOnlySpan`1 data, Boolean isNull, SerializationContext context)
   at Confluent.Kafka.Consumer`2.Consume(Int32 millisecondsTimeout)
   --- End of inner exception stack trace ---
   at Confluent.Kafka.Consumer`2.Consume(Int32 millisecondsTimeout)
   at Confluent.Kafka.Consumer`2.Consume(CancellationToken cancellationToken)
   at Confluent.Kafka.Examples.AvroSpecific.Program.KafkaConsume(List`1 topics) in /Users/aureliosaraiva/projects/xxx/ConsoleKafka/ConsoleKafka/Program.cs:line 90
Consume error: Local: Key deserialization error
```

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Confluent.Kafka" />
    <None Remove="Confluent.Apache.Avro" />
    <None Remove="Confluent.SchemaRegistry.Serdes.Avro" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Confluent.Kafka" Version="1.8.2" />
    <PackageReference Include="Confluent.SchemaRegistry.Serdes.Avro" Version="1.8.2" />
  </ItemGroup>
</Project>
```

Checklist
=========

Please provide the following information:
 - [x] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [x] Confluent.Kafka nuget version.
 - [x] Apache Kafka version.
 - [x] Client configuration.
 - [x] Operating system (MacOS).
 - [x] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
it may be a problem in the avro library - what is the schema of event_tracked_v1? 
suggest trying to narrow it down. you could use the `Ignore` type to only read keys or values in order to determine whether it's the key or value causing the problem. if it's the value, then you could try modifying the schema to see where the issue is.
unfortunately i can't tell from the information provided.
