### ISSUE TITLE
getKafkaTopicHandle() not thread-safe

### ISSUE THREAD

**Issue by edenhill** [confluentinc/confluent-kafka-dotnet#18]
The topic handle cache isn't thread-safe as seen when trying to produce from multiple threads:
```
DEBUG: 2017-01-25 13:01:00: Produce on thread 7
DEBUG: 2017-01-25 13:01:00: Produce on thread 8

Unhandled Exception: System.ArgumentException: An item with the same key has already been added. Key: test.net
   at System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException(Object key)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Confluent.Kafka.Internal.SafeDictionary`2.Add(TKey key, TValue val)
   at Confluent.Kafka.Producer.getKafkaTopicHandle(String topic)
   at Confluent.Kafka.Producer.Produce(String topic, Byte[] val, Int32 valOffset, Int32 valLength, Byte[] key, Int32 keyOffset, Int32 keyLength, Nullable`1 timestamp, Int32 partition, Boolean blockIfQueueFull, IDeliveryHandler deliveryHandler)
   at Confluent.Kafka.Producer.ProduceAsync(String topic, Byte[] key, Byte[] val, IDeliveryHandler deliveryHandler, Nullable`1 timestamp, Nullable`1 partition, Boolean blockIfQueueFull)
   at Confluent.Kafka.SerializingProducer`2.ProduceAsync(String topic, TKey key, TValue val, Nullable`1 timestamp, Nullable`1 partition, Boolean blockIfQueueFull)
   at Confluent.Kafka.Producer`2.ProduceAsync(String topic, TKey key, TValue val, Nullable`1 timestamp, Nullable`1 partition, Boolean blockIfQueueFull)
   at Confluent.Kafka.VerifiableClient.VerifiableProducer.Produce(String topic, String value)
   at Confluent.Kafka.VerifiableClient.VerifiableProducer.TimedProduce(Object ignore)
   at Confluent.Kafka.VerifiableClient.VerifiableProducer.<Run>b__11_0(Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()
```

The problem is most likely the unprotected read-write race in getKafkaTopicHandle() that first checks if topic is in the dict and then inserts it (if it isnt). That entire cycle needs to be done in one locked operation.

**Comment by mhowlett** [comment]
reopening. see comments in PR #20.

**Comment by mhowlett** [comment]
clarifying the status of this: 

there is potential for a memory leak if two threads try to produce to a topic for the first time at the same time. this will happen rarely and the consequence would not normally cause any problems. considered low priority compared to other open issues.

**Comment by kuskmen** [comment]
I suppose this is no longer relevant? I saw implementation now is way different. Or needs fix in previous versions? If you elaborate I might throw a glance at it.

Regards,
kuskmen

**Comment by mhowlett** [comment]
thanks @kuskmen - iirc this was resolved and topic handles are no longer used by the core methods. that said, they are required for custom partitioners which I'll probably add soon, and I'll be considering the code carefully myself then.
