### ISSUE TITLE
Can no longer even import confluent-kafka after upgrading 1.8.2 > 1.9.0 (Apple M1 pro)

### ISSUE THREAD

**Issue by ianbruton** [confluentinc/confluent-kafka-dotnet#1841]
Description
===========

upgrading 1.8.2 > 1.9.0 broke my code and I am unsure why. I am no longer even able to import confluent-kafka

context:

machine running the code : 
<img width="208" alt="image" src="https://user-images.githubusercontent.com/4050482/174327341-e8ba6405-010d-4777-9ff4-9419c123ae89.png">

kafka is located in AWS running through MSK (version 2.6.2)

not using any other confluent services or libraries other than confluent-kafka

How to reproduce
================

upgrade to 1.9.0 and import confluent-kafka

here is some terminal output (with some paths censored and spacing of commands)

```
(python-3.8.13) $ pip list
Package         Version
--------------- -------
confluent-kafka 1.8.2
Faker           13.13.0
pip             22.1.2
python-dateutil 2.8.2
setuptools      56.0.0
six             1.16.0

(python-3.8.13) $ python3
Python 3.8.13 (default, May  2 2022, 11:54:35)
[Clang 13.1.6 (clang-1316.0.21.2.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import confluent_kafka
>>> exit()

(python-3.8.13) $ pip uninstall confluent_kafka
Found existing installation: confluent-kafka 1.8.2
Uninstalling confluent-kafka-1.8.2:
  Would remove:
    /path/to/python/install/python-3.8.13/LICENSE.txt
    /path/to/python/install/python-3.8.13/lib/python3.8/site-packages/confluent_kafka-1.8.2-py3.8.egg-info
    /path/to/python/install/python-3.8.13/lib/python3.8/site-packages/confluent_kafka/*
Proceed (Y/n)? y
  Successfully uninstalled confluent-kafka-1.8.2

(python-3.8.13) $ pip install confluent_kafka
Collecting confluent_kafka
  Using cached confluent-kafka-1.9.0.tar.gz (110 kB)
  Preparing metadata (setup.py) ... done
Using legacy 'setup.py install' for confluent_kafka, since package 'wheel' is not installed.
Installing collected packages: confluent_kafka
  Running setup.py install for confluent_kafka ... done
Successfully installed confluent_kafka-1.9.0

(python-3.8.13) $ pip list
Package         Version
--------------- -------
confluent-kafka 1.9.0
Faker           13.13.0
pip             22.1.2
python-dateutil 2.8.2
setuptools      56.0.0
six             1.16.0

(python-3.8.13) $ python3
Python 3.8.13 (default, May  2 2022, 11:54:35)
[Clang 13.1.6 (clang-1316.0.21.2.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import confluent_kafka
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/path/to/python/install/python-3.8.13/lib/python3.8/site-packages/confluent_kafka/__init__.py", line 19, in <module>
    from .deserializing_consumer import DeserializingConsumer
  File "/path/to/python/install/python-3.8.13/lib/python3.8/site-packages/confluent_kafka/deserializing_consumer.py", line 19, in <module>
    from confluent_kafka.cimpl import Consumer as _ConsumerImpl
ImportError: dlopen(/path/to/python/install/python-3.8.13/lib/python3.8/site-packages/confluent_kafka/cimpl.cpython-38-darwin.so, 0x0002): symbol not found in flat namespace '_rd_kafka_AclBindingFilter_new'
```

Checklist
=========

Please provide the following information:
 - [x] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ ] Confluent.Kafka nuget version.
 - [x] Apache Kafka version.
 - [ ] Client configuration.
 - [x] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
please ask the same question in https://github.com/confluentinc/confluent-kafka-python
