### ISSUE TITLE
Mornitoring interceptor inside docker container

### ISSUE THREAD

**Issue by paveldayneko** [confluentinc/confluent-kafka-dotnet#1871]
Description
===========

I'm having issue running kafka consumer with monitoring interceptor inside docker container.
Local windows environment works just fine. 

How to reproduce
================

Create kafka consumer and make it use confluent-monitoring-interceptor
``` c#
  var consumerConfig = new ConsumerConfig
  {
      BootstrapServers = _options.Value.BootstrapServers,
      GroupId = groupId,
      PluginLibraryPaths = "monitoring-interceptor"
  };
````

build application inside docker container and install monitoring-interceptor package

```docker
FROM mcr.microsoft.com/dotnet/sdk:6.0-focal AS build
WORKDIR /src
COPY . .
RUN dotnet restore "#{pseudo_proj_path}"
RUN dotnet publish "#{pseudo_proj_path}" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:6.0-focal  AS final

RUN apt-get update && apt-get install -y gnupg2 && apt-get install -y  software-properties-common && apt install wget
RUN wget -qO - https://packages.confluent.io/deb/7.2/archive.key | apt-key add -
RUN add-apt-repository "deb [arch=amd64] https://packages.confluent.io/deb/7.2 stable main"
RUN add-apt-repository "deb https://packages.confluent.io/clients/deb focal main"
RUN apt-get update && apt-get install confluent-librdkafka-plugins

WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "#{pseudo_dll}"]
```

try to build and run image and following error will appear
  

>  Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
>  ---> System.ArgumentException: dlopen() failed: /usr/lib/x86_64-linux-gnu/monitoring-interceptor.so: undefined symbol: rd_kafka_conf_dup_filter (plugin monitoring-interceptor)
>   at Confluent.Kafka.Impl.SafeConfigHandle.Set(String name, String value)
>   at Confluent.Kafka.Consumer`2.<>c__DisplayClass77_0.<.ctor>b__3(KeyValuePair`2 kvp)
>   at System.Collections.Generic.List`1.ForEach(Action`1 action)
>   at Confluent.Kafka.Consumer`2..ctor(ConsumerBuilder`2 builder)
>   at Confluent.Kafka.ConsumerBuilder`2.Build()
> 

Checklist
=========

Please provide the following information:
 - [x] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [x] Confluent.Kafka nuget version. 1.9.0
 - [x] Apache Kafka version. not relevant
 - [x] Client configuration.
 - [x] Operating system. aspnet:6.0-focal docker image
 - [x] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
Interesting. does it work with an earlier version of Confluent.Kafka?

**Comment by paveldayneko** [comment]
To be honest I'm not even sure that this is even .net clinet's issue, it might be monitoring-interceptor's bug, but I can't find a place where to sumbit it as this product is not open sourced

**Comment by conan-goldsmith** [comment]
I have seen this issue occurring if there is missing repositories (or stale cache)
@paveldayneko Could you try the below commands?
add-apt-repository --remove "deb https://packages.confluent.io/clients/deb $(lsb_release -cs) main"
apt purge confluent-librdkafka-plugins
apt install confluent-librdkafka-plugins

**Comment by mhowlett** [comment]
Monitoring interceptors were an important part of making the message delivery capability that used to be in Confluent Control Center work. I believe that functionality has now been hidden by default, and the monitoring interceptors are not used for much anymore. So 1. for this reason I'm marking this as low priority. 2. i'm wondering if you're sure you need this, or just following some instructions somewhere?

**Comment by paveldayneko** [comment]
Thanks for clarification @mhowlett. After a bit of consultancy from Confluent we decided that interceptor is not needed indeed. We will stick to JMX metrics emmited by Kafka cluster and our clients and that should be enough.
