### ISSUE TITLE
my kafka always exit

### ISSUE THREAD

**Issue by easyboot** [confluentinc/confluent-kafka-dotnet#1902]
Description
===========

In Windows, kafka often exits automatically, prompting that another program is using this file, and the process cannot access it.

D:\JSJPService\kafka\log\kafka-logs\JSJP.InfusionBag.Message-0\00000000000000000000.index.deleted: 另一个程序正在使用此文件，进程无法访问。
                at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
                at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
                at java.base/sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:317)
                at java.base/sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:293)
                at java.base/java.nio.file.Files.move(Files.java:1432)
                at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:932)
                ... 26 more

How to reproduce
================

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ ] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
There are known issues running Kafka on Windows and it is not supported.

You can run it under WSL2 however.  https://www.confluent.io/blog/set-up-and-run-kafka-on-windows-linux-wsl-2/
