### ISSUE TITLE
Confluent-kafka-dotnet - Consumer occasionally dies 

### ISSUE THREAD

**Issue by mshahins** [confluentinc/confluent-kafka-dotnet#1916]
Description
===========
We are using Confluent.Kafka 1.7.0. Attached is our code. 

We are listening to topic; which is not very chatty. Sometimes for days we don't get any messages on that topic. We have also added debug log. 

Very occasionally our consumer just dies with ConsumeException; as practice we are also forfeiting consuming messages as well. 

Code : 

    ```
    public async Task<IEsmeEvent<T>> ConsumeAsync<T>(CancellationToken stoppingToken = default)
            where T : class
        {
            ConsumeResult<string, string> consumerResult = null;

            try
            {
                consumerResult = await Task.FromResult(_consumer.Value.Consume(stoppingToken)).ConfigureAwait(false);
                _logger.Debug(
                    $"Consumed message '{consumerResult.Message.Value}' from topic {consumerResult.Topic}, partition {consumerResult.Partition}, offset {consumerResult.Offset}");
                var @event = _eventFactory.Create<T>(consumerResult.Topic, consumerResult.Message.Value, consumerResult.Message.Key, consumerResult.Offset.Value);
                _consumer.Value.StoreOffset(consumerResult);
                return @event;
            }
            catch (JsonException ex)
            {
                _logger.Error(
                    $"Deserialization failed while processing message from topic [{consumerResult?.Topic}], partition [{consumerResult?.Partition}], offset [{consumerResult?.Offset}]");
                throw new EsmeConsumeException($"Error consuming on topic [{_consumerOptions.Topic}].", ex);
            }
            catch (ConsumeException ex) //This exception get's thrown.
            {
                _logger.Error(
                    $"Consume failed with [ErrorCode={ex.Error.Code}] [Reason={ex.Error.Reason} [OffSet={ex.Error.Code}]] {ex.ConsumerRecord.Message.}");
                throw new EsmeConsumeException($"Error consuming on topic [{_consumerOptions.Topic}].", ex);
            }
            catch (Exception ex)
            {
                _logger.Error(
                    $"Consume failed with [Message={ex.Message}] [InnerException={ex.InnerException} [Source={ex.Source}]]");
                throw new EsmeConsumeException($"Error consuming on topic [{_consumerOptions.Topic}].", ex);
            }
        }

        private IConsumer<string, string> CreateConsumer(string topic)
        {
            var clientConfig = _clientOptions.Value.ToClientConfig();
            var config = new ConsumerConfig(clientConfig)
            {
                ClientId = _clientOptions.Value.ClientId,
                GroupId = _consumerOptions.GroupId,
                SessionTimeoutMs = _clientOptions.Value.BrokerSessionTimeoutMs == 0
                    ? EsmeConsumerClientOptions.DefaultBrokerSessionTimeoutMs
                    : _clientOptions.Value.BrokerSessionTimeoutMs,
                EnableAutoCommit = true,
                EnableAutoOffsetStore = false
            };

            ConsumerBuilder<string, string> builder;

            if (string.IsNullOrWhiteSpace(_clientOptions.Value.ConsumerDebugSettings))
            {
                builder = new ConsumerBuilder<string, string>(config)
                    .SetErrorHandler((_, error) => _logger.Error(error.GetStringToLog(config.ClientId)))
                    .SetLogHandler((_, message) => _logger.Debug(message.GetStringToLog()));
            }
            else
            {
                config.Debug = _clientOptions.Value.ConsumerDebugSettings.Trim();
                builder = new ConsumerBuilder<string, string>(config)
                    .SetErrorHandler((_, error) => _logger.ScopedLog(LogLevel.Error, error.GetStringToLog(config.ClientId), scopeKey: LogScopeKey, scopeValue: LogScopeValue))
                    .SetLogHandler((_, message) => _logger.ScopedLog(LogLevel.Debug, message.GetStringToLog(), scopeKey: LogScopeKey, scopeValue: LogScopeValue));
            }

            var consumer = builder.Build();
            consumer.Subscribe(topic);
            return consumer;
        }
```

Configuration : 

```
   "Client": {
      "Server": "xxxxx",
      "ClientId": "Local.Local.Loss",
      "ApiKey": "xxxxx",
      "Secret": "xxxx",
      "RedundancyStrategy": "Full",

      //Consumer settings
      "BrokerSessionTimeoutMs": 15000,
      "ConsumerDebugSettings": "consumer,cgrp,topic,fetch",

      //Producer settings
      "ProducerDebugSettings": "broker,topic,msg"
    }
```

Log from our Application : 

```
 2022-10-03 18:19:54,815 ERROR Ag.Esme.Kafka.KafkaConsumer: Consume failed with [ErrorCode=Local_MaxPollExceeded] [Reason=Local: Maximum application poll interval (max.poll.interval.ms) exceeded [OffSet=Local_MaxPollExceeded]]
 2022-10-03 18:19:54,894 ERROR Ag.Esme.EventStream.EsmeConsumerProcessor: The client [TreasuryClaimEventHandler] has encountered an unrecoverable failure. Error: Ag.Esme.Abstractions.EventStream.EsmeConsumeException: Error consuming on topic [LossTopic]. ---> Confluent.Kafka.ConsumeException: Local: Maximum application poll interval (max.poll.interval.ms) exceeded
   at Confluent.Kafka.Consumer`2.Consume(Int32 millisecondsTimeout)
   at Confluent.Kafka.Consumer`2.Consume(CancellationToken cancellationToken)
   at Ag.Esme.Kafka.KafkaConsumer.<ConsumeAsync>d__9`1.MoveNext()
   --- End of inner exception stack trace ---
   at Ag.Esme.Kafka.KafkaConsumer.<ConsumeAsync>d__9`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ag.Esme.EventStream.EsmeConsumerProcessor`1.<GetEventAsync>d__12.MoveNext()
```

Questions : 

Debug Log is attached. I do see Consumer leaving at 18:16 in Debug Log; but it seems librdrakafka keeps running internally. And we are throwing exception out. What would be correct way to catch this and recover from this error; also is this regular behavior or client and we need to account for this in our code ? 

How to reproduce
================

We are not able to reproduce consistently; it happens very occasionally. We have attached Application Log and Debug Log.

Checklist
=========

Please provide the following information:
 - [ Attached Code snippet ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ 1.7.0 ] Confluent.Kafka nuget version.
 - [ We are using Confluent Cloud ] Apache Kafka version.
 - [ Attached ] Client configuration.
 - [Windows ] Operating system.
 - [ Attached ] Provide logs [(with](u
[DebugLog.txt](https://github.com/confluentinc/confluent-kafka-dotnet/files/9715752/DebugLog.txt)
rl) "debug" : "..." as necessary in configuration).
 - [We are using Confluent Cloud ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
> Maximum application poll interval

this implies the time between calls to `Consume` was longer than `MaxPollTimeoutMs`, which is 5 minutes by default. Can your processing of each message take longer than this?

**Comment by mshahins** [comment]
No; it is not taking longer than 5 minutes. When this happened there were no messages to Consume. You can check in Debug Log; it does not show any messages being consumed at all. This has been mystery for us. 

Is it possible that when _consumer.Consme() is called which internally uses libdrkafka; that one took longer time or some internal thread got haywire ? 

2. Also messege in debug log says this : 

`2022-10-03 18:19:54,815 DEBUG Ag.Esme.Kafka.KafkaConsumer: ClientId:Dev.AppBatchDev.LossCalculator#consumer-3 Level:Warning Facility:MAXPOLL Message: [thrd:main]: Application maximum poll interval (300000ms) exceeded by **1996859793ms** (adjust max.poll.interval.ms for long-running message processing): leaving group.`

1996859793ms is unusually long time. 

3. If Consumers leaves the group; does libdrakafka client tries to reconnect again or it stops operating further ?

Thanks

**Comment by mshahins** [comment]
I don't mind upgrading; but is it known problem in 1.7 ? I don't have consistent way to reproduce this bug; so not sure even after upgrading it will fix it.

**Comment by mhowlett** [comment]
there are significant fixes to the consumer post 1.7 which may be related, though this issue specifically is not familiar to me.

**Comment by mshahins** [comment]
If it helps - many times we don't get messages for days on this topic. If topic is not getting messages for long period of time (sometimes several days consecutively); is there any logic in broker or in client where it will force to leave the group and it will generate ConsumeException ?

**Comment by mhowlett** [comment]
a possible work around would be to dispose and re-create the consumer periodically (say every hour).

**Comment by mhowlett** [comment]
you could also assign to the topic partition(s) directly - since your throughput is so low you don't have any need for a consumer group.

**Comment by Plotso** [comment]
Hello, @mhowlett. 

We're facing exactly the same error mentioned in this issue & also in https://github.com/confluentinc/confluent-kafka-dotnet/issues/1228. We are using latest confluent kafka (1.9.3) and our apps in production just randomly stuck from time to time. We have N pods of a service deployed to k8s and working with same consumerGroup. After some period of time, suddenly one of the pods gets stuck in .Consume(cancellationToken) method. 
![image](https://user-images.githubusercontent.com/21315460/202557481-183145b1-f053-4c6b-8145-6b251e33af15.png)
From this picture we can see that we have a log right before .Consume(cancellationToken) logged at 19:04:40.
After 12s we got following error:
`2022-11-17T21:04:52+02:00 %4|1668711892.043|MAXPOLL|rdkafka#consumer-6| [thrd:main]: Application maximum poll interval (10000ms) exceeded by 247ms (adjust max.poll.interval.ms for long-running message processing): leaving group`
Our max.poll.interval.ms is set to 10s. So after that time we suddenly got the poll error. 
Here is a look at our code including the attached log.
![image](https://user-images.githubusercontent.com/21315460/202558057-e420e878-f645-4e39-a112-16b1f30c5f59.png)
![image](https://user-images.githubusercontent.com/21315460/202558154-63af6776-eabf-47fb-91e9-05b921c4c702.png)

So, we do reach that point, our cancellationToken has no cancellation requested, but the consumer for some reason doesn't poll at all. According to the summary of the consume method, it's supposed to poll until it receives a message:
![image](https://user-images.githubusercontent.com/21315460/202558433-04753258-2f8f-4079-a9b8-029c4799014f.png)

Could you please advice on how to fix this? The worst part is this error from above cannot be caught in try/catch, therefore, we cannot just rebuild & re-subscribe our consumer.

**Comment by anchitj** [comment]
@mshahins This should not be considered as a fatal error. One the subsequent `Consume()` call the consumer will join the group and will resume the consumption.

@Plotso Can you provide debug logs and your consumer config?

**Comment by mshahins** [comment]
@anchitj - Hi I want to delete this issue permanently. I don't have the ability to delete this issue. As an owner of this repo can you please delete this issue? Thanks

**Comment by ksdvishnukumar** [comment]
Hi @mshahins, Did your issue for resolved? If yes it will help others the solution
