### ISSUE TITLE
The reader's MaxDepth of 64 has been exceeded exception while de-serializing message

### ISSUE THREAD

**Issue by RohitPatil-Maersk** [confluentinc/confluent-kafka-dotnet#1952]
In my .Net 6 console app, I am using AvroDeserializer to deserialize message consumed from the topic. Below is the line of code.
_deserializedMessage.Value = valueDeserializer.Deserialize(consumeResult.Message.Value, false,
                    new SerializationContext(MessageComponentType.Value, consumeResult.Topic,
                        consumeResult.Message.Headers));_

When AvroDeserializer.Deserialize() is called, below exception is thrown (removed project specific lines):

_System.Reflection.TargetInvocationException
  HResult=0x80131604
  Message=Exception has been thrown by the target of an invocation.
  Source=System.Private.CoreLib
  StackTrace:
   at System.RuntimeFieldHandle.GetValue(RtFieldInfo field, Object instance, RuntimeType fieldType, RuntimeType declaringType, Boolean& domainInitialized)
   at System.Reflection.RtFieldInfo.GetValue(Object obj)
   at Confluent.SchemaRegistry.Serdes.SpecificDeserializerImpl`1..ctor(ISchemaRegistryClient schemaRegistryClient)
   at Confluent.SchemaRegistry.Serdes.AvroDeserializer`1.<DeserializeAsync>d__3.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Confluent.Kafka.SyncOverAsync.SyncOverAsyncDeserializer`1.Deserialize(ReadOnlySpan`1 data, Boolean isNull, SerializationContext context)_

_Inner Exception 2:
JsonReaderException: The reader's MaxDepth of 64 has been exceeded. Path 'fields[8].type.fields[2].type[1].fields[3].type[1].fields[7].type[1].fields[0].type[1].fields[5].type[1].items.fields[4].type[1].fields[8].type[1].fields[3].type[1].fields[9].type[1].fields[2].type.fields[9].type[1].fields[2].type.fields[9].type[1].fields[2].type.fields[9].type[1].items.fields[0]', line 1, position 16699._

What I am doubting is, because the json message pushed on the topic is deeply nested, the default MaxDepth value of JsonDeserializer is not sufficient. But there is no way for me to change the MaxDepth value as the JsonSerializer.
===========

How to reproduce
================
Try to deserialize any deeply nested json message using AvroDeserializer

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ ] Confluent.Kafka nuget version : v1.9.3
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system: Windows
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue: Yes

**Comment by RohitPatil-Maersk** [comment]
Have I reported this issue correctly? Am I missing anything to get an attention?

**Comment by anchitj** [comment]
Hi @RohitPatil-Maersk, Can you please provide a sample message and the code you were trying to run which encountered this issue?

**Comment by RohitPatil-Maersk** [comment]
hi @anchitj, the json contains a data which I cannot share outside my organization. Is there any other way where I can provide you more info?

**Comment by emasab** [comment]
Hello @RohitPatil-Maersk. The JsonSchemaGeneratorSettings can be passed [here](https://github.com/confluentinc/confluent-kafka-dotnet/blob/19d4fa19e02d775946752fd350aff7570b1e29fd/src/Confluent.SchemaRegistry.Serdes.Json/JsonDeserializer.cs#L65) that can contain `ActualSerializerSettings`, where MaxDepth can be set, like in [this](https://www.newtonsoft.com/json/help/html/MaxDepth.htm) example.

**Comment by anchitj** [comment]
Hi, Is this still an issue?

**Comment by RohitPatil-Maersk** [comment]
Hi, we haven't heard soon after we created this issue, so we asked our producer to change the schema to reduce nesting.  I tried to apply the solution provided by emasab above but couldn't find a way to apply it for Avro de-serialization.
