### ISSUE TITLE
Confluent Avro Schema Registry HttpRequestException: An error occurred while sending the request.

### ISSUE THREAD

**Issue by vivere-dally** [confluentinc/confluent-kafka-dotnet#1960]
Description
===========
I have a docker schema registry container running on `localhost:5001`. Calling endpoints from terminal works well via curl, however the dotnet client does not seem to work.

Full stack trace:
```
Confluent.Kafka.ProduceException`2[Confluent.Kafka.Null,Playground.ConsoleApp.User]: Local: Value serialization error
 ---> System.Net.Http.HttpRequestException: [http://localhost:5001/] HttpRequestException: An error occurred while sending the request.
   at Confluent.SchemaRegistry.RestService.ExecuteOnOneInstanceAsync(Func`1 createRequest)
   at Confluent.SchemaRegistry.RestService.RequestAsync[T](String endPoint, HttpMethod method, Object[] jsonBody)
   at Confluent.SchemaRegistry.RestService.RegisterSchemaAsync(String subject, Schema schema, Boolean normalize)
   at Confluent.SchemaRegistry.CachedSchemaRegistryClient.RegisterSchemaAsync(String subject, Schema schema, Boolean normalize)
   at Confluent.SchemaRegistry.Serdes.SpecificSerializerImpl`1.Serialize(String topic, T data, Boolean isKey)
   at Confluent.SchemaRegistry.Serdes.AvroSerializer`1.SerializeAsync(T value, SerializationContext context)
   at Confluent.Kafka.Producer`2.ProduceAsync(TopicPartition topicPartition, Message`2 message, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Confluent.Kafka.Producer`2.ProduceAsync(TopicPartition topicPartition, Message`2 message, CancellationToken cancellationToken)
```

How to reproduce
================
Container:
```yml
  kafka-schema-registry:
    # image: bitnami/schema-registry
    image: confluentinc/cp-schema-registry
    container_name: kafka-schema-registry
    ports:
      - '5001:8081'
    restart: always
    depends_on:
      - kafka
    environment:
      - SCHEMA_REGISTRY_HOST_NAME=schemaregistry
      - SCHEMA_REGISTRY_LISTENERS=http://0.0.0.0:8081
      - SCHEMA_REGISTRY_DEBUG=true
```

C# code:
```c#
string schemaRegistryUrl = "localhost:5001";
using var schemaRegistry = new CachedSchemaRegistryClient(new SchemaRegistryConfig
{
    Url = schemaRegistryUrl
});
using var producer = new ProducerBuilder<Null, User>(new ProducerConfig
{
    BootstrapServers = bootstrapServers
})
    .SetValueSerializer(new AvroSerializer<User>(schemaRegistry, new AvroSerializerConfig()))
    .Build();
var result = await producer.ProduceAsync("playground-user", new Message<Null, User>() { Value = user });
```

class user:
```c#
    partial class User : ISpecificRecord
    {
        public static Avro.Schema _SCHEMA = Avro.Schema.Parse("{\r\n    \"type\": \"record\",\r\n    \"name\": \"TestObject\",\r\n    \"namespace\": \"ca.dataedu\",\r\n    \"fields\": [{\r\n        \"name\": \"name\",\r\n        \"type\": [\"null\", \"string\"],\r\n        \"default\": null\r\n    }, {\r\n        \"name\": \"password\",\r\n        \"type\": [\"null\", \"string\"],\r\n        \"default\": null\r\n    }]\r\n}");
        public string Name { get; set; }
        public string Password { get; set; }

        public virtual Avro.Schema Schema
        {
            get
            {
                return _SCHEMA;
            }
        }

        public virtual object Get(int fieldPos)
        {
            return fieldPos switch
            {
                0 => this.Name,
                1 => this.Password,
                _ => throw new ArgumentException($"Bad index {fieldPos}"),
            };
        }

        public virtual void Put(int fieldPos, object fieldValue)
        {
            switch (fieldPos)
            {
                case 0:
                    this.Name = (string)fieldValue;
                    break;
                case 1:
                    this.Password = (string)fieldValue;
                    break;
                default:
                    throw new ArgumentException($"Bad index {fieldPos}");
            }
        }
    }
```

Checklist
=========

Please provide the following information:
 - [x] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [x] Confluent.Kafka nuget version.
 - [x] Apache Kafka version.
 - [x] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by anchitj** [comment]
@vivere-dally I would suggest going through the Avro examples in the repo https://github.com/confluentinc/confluent-kafka-dotnet/blob/89b7c98a75f4ae4b988c0ebff9eb7191df9e3a99/examples/AvroSpecific/Program.cs to find out the issue. Examples given in the repo do work with the client.

**Comment by Katrell01** [comment]
Any Update of this issue?
