### ISSUE TITLE
`ListGroup` throws `OverflowException`

### ISSUE THREAD

**Issue by dstelljes** [confluentinc/confluent-kafka-dotnet#1995]
Description
===========

`ListGroup` intermittently throws `OverflowException` from the librdkafka bindings. It appears to happen when group membership information reaches a certain size.

How to reproduce
================

With Confluent.Kafka 2.0.2 on .NET 6:

```csharp
using Confluent.Kafka;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

var broker = $"bootstrap:9092";
var groupId = $"test-group-{Guid.NewGuid()}";
var topicName = "test-topic";

var adminConfig = new AdminClientConfig
{
    BootstrapServers = broker,
};

var consumerConfig = new ConsumerConfig
{
    BootstrapServers = broker,
    EnableAutoCommit = false,
    GroupId = groupId,
};

var admin = new AdminClientBuilder(adminConfig)
    .Build();

for (var i = 0; i < 10; i++)
{
    var consumer = new ConsumerBuilder<Ignore, Ignore>(consumerConfig).Build();

    consumer.Subscribe(topicName);
    await Task.Delay(TimeSpan.FromSeconds(5));

    var info = admin.ListGroup(groupId, TimeSpan.FromSeconds(5));
    Console.WriteLine($"{i}: {groupId} has {info.Members.Count} members");
}
```

After a few members (locally, 3 seems to do it), this program crashes:

```
0: test-group-496fec82-92e4-4d54-9d51-ce769e149134 has 1 members
1: test-group-496fec82-92e4-4d54-9d51-ce769e149134 has 2 members
Unhandled exception. System.OverflowException: Arithmetic operation resulted in an overflow.
   at System.IntPtr.op_Explicit(IntPtr value)
   at Confluent.Kafka.Impl.SafeKafkaHandle.CopyBytes(IntPtr ptr, IntPtr len)
   at Confluent.Kafka.Impl.SafeKafkaHandle.<>c.<ListGroupsImpl>b__73_3(rd_kafka_group_member_info mi)
   at System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.SelectRangeIterator`1.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Confluent.Kafka.Impl.SafeKafkaHandle.<>c.<ListGroupsImpl>b__73_1(rd_kafka_group_info gi)
   at System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.SelectRangeIterator`1.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Confluent.Kafka.Impl.SafeKafkaHandle.ListGroupsImpl(String group, Int32 millisecondsTimeout)
   at Confluent.Kafka.Impl.SafeKafkaHandle.ListGroup(String group, Int32 millisecondsTimeout)
   at Confluent.Kafka.AdminClient.ListGroup(String group, TimeSpan timeout)
   at Program.<Main>$(String[] args) in /workspaces/ubuntu/Program.cs:line 35
   at Program.<Main>(String[] args)
```

Full logs [here](https://github.com/confluentinc/confluent-kafka-dotnet/files/10678676/run.log) with `Debug = "all"` on `adminConfig`.

The problem is not reproducible with Confluent.Kafka 1.9.3.

Checklist
=========

Please provide the following information:
 - [x] A complete (i.e. we can run it), minimal program demonstrating the problem: above
 - [x] Confluent.Kafka NuGet version: 2.0.2
 - [x] Apache Kafka version: 2.7 (Confluent Platform 6.1.2)
 - [x] Client configuration: above
 - [x] Operating system: macOS (M1), Ubuntu 22.10 (x64)
 - [x] Provide logs (with "debug" : "..." as necessary in configuration): [run.log](https://github.com/confluentinc/confluent-kafka-dotnet/files/10678676/run.log)
 - [ ] Provide broker log excerpts: n/a
 - [ ] Critical issue.

**Comment by Willimaendu** [comment]
We encounter the exactly same problem. Would be very helpful to investigate and fix this.

**Comment by bentdan** [comment]
Any update on this?  Thanks!

**Comment by anchitj** [comment]
Thank you for reporting the bug. I am currently investigating the issue.

**Comment by anchitj** [comment]
This should be fixed in the coming release.

**Comment by BEagle1984** [comment]
When do you plan to release the next version including this fix?
