### ISSUE TITLE
[Obsolete] missing attribute usage

### ISSUE THREAD

**Issue by plachor** [confluentinc/confluent-kafka-dotnet#1998]
Hi recently I've tried to update library from 1.9.0 to 2.0.2. I've encountered some errors in `IAdminClient.ListGroups` API:
```
System.OverflowException: Arithmetic operation resulted in an overflow.
   at System.IntPtr.op_Explicit(IntPtr value)
   at Confluent.Kafka.Impl.SafeKafkaHandle.CopyBytes(IntPtr ptr, IntPtr len)
   at Confluent.Kafka.Impl.SafeKafkaHandle.<>c.<ListGroupsImpl>b__73_3(rd_kafka_group_member_info mi)
   at System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.SelectRangeIterator`1.ToList()
   at Confluent.Kafka.Impl.SafeKafkaHandle.<>c.<ListGroupsImpl>b__73_1(rd_kafka_group_info gi)
   at System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.SelectRangeIterator`1.ToList()
   at Confluent.Kafka.Impl.SafeKafkaHandle.ListGroupsImpl(String group, Int32 millisecondsTimeout)
   at Confluent.Kafka.Impl.SafeKafkaHandle.ListGroups(Int32 millisecondsTimeout)
   at Confluent.Kafka.AdminClient.ListGroups(TimeSpan timeout)
```

While checking what changed I found out someone added comment:
>        ///     DEPRECATED.
>        ///     Superseded by ListConsumerGroups and DescribeConsumerGroups.

**But he has not added `[Obsolete("Do something comment")]` attribute.** This not good because no one will know you wish everyone to move to new API. If you add proper obsolete than IDE will notify clients of your library that they should take some action.

**Comment by anchitj** [comment]
Thanks for the feedback. I've created a PR to fix this.

**Comment by mohammed-saalim** [comment]
Hi @plachor @mhowlett 👋

I've opened a PR to address this issue: #2591

The changes add [Obsolete("Superseded by ListConsumerGroupsAsync and DescribeConsumerGroupsAsync. This method will be removed in a future release.")] to both 
ListGroups and ListGroup on the IAdminClient interface and the AdminClient implementation, along with reflection-based unit tests to prevent regression.

This supersedes the abandoned #2014.Regarding the follow-up comment about deprecated config properties in Config_gen.cs
 — since that file is auto-generated, it would require changes to the code generator and is out of scope for this PR.
