### ISSUE TITLE
2.1.0 broke test.mock.num.brokers

### ISSUE THREAD

**Issue by mac2000** [confluentinc/confluent-kafka-dotnet#2038]
Description
===========

After upgrading from `2.0.2` to `2.1.0` unit tests utilising `test.mock.num.brokers` are failing with error `Confluent.Kafka.ConsumeException: Subscribed topic not available: UnitTest: Broker: Unknown topic or partition`

How to reproduce
================

```cs
public class Example
{
    public void SampleReproduction()
    {

        var adminClient = new AdminClientBuilder(new ClientConfig(new Dictionary<string, string> { {"bootstrap.servers", "localhost:9200"}, {"test.mock.num.brokers", "3"} })).Build();
        var bootstrapServers = string.Join(",", adminClient.GetMetadata(TimeSpan.FromSeconds(1)).Brokers.Select(b => $"{b.Host}:{b.Port}"));

        var producer = new ProducerBuilder<Null, string>(new ProducerConfig { BootstrapServers = bootstrapServers }).Build();
        var consumer = new ConsumerBuilder<Ignore, string>(new ConsumerConfig { BootstrapServers = bootstrapServers, GroupId = "ExampleUnitTest", AutoOffsetReset = AutoOffsetReset.Earliest }).Build();
        var message = new Message<Null, string> { Value = "Test" };
        var topic = "UnitTest";

        producer.Produce(topic, message);
        consumer.Subscribe(topic);

        var actual = consumer.Consume(TimeSpan.FromSeconds(10)).Message.Value;

        actual.Should().Be(message.Value);
    }
}
```

stacktrace contains nothing interesting

```log
Confluent.Kafka.ConsumeException: Subscribed topic not available: UnitTest: Broker: Unknown topic or partition

Confluent.Kafka.ConsumeException
Subscribed topic not available: UnitTest: Broker: Unknown topic or partition
   at Confluent.Kafka.Consumer`2.Consume(Int32 millisecondsTimeout)
   at Confluent.Kafka.Consumer`2.Consume(TimeSpan timeout)
   at Tests.ExampleUnitTestForConsumersAndOrProducers.SampleReproduction() in /Users/mac/github.com/rabotaua/kafka/Tests/ExampleUnitTestForConsumersAndOrProducers.cs:line 43
```

I have added log handler to admin client, but there is only one record:

```log
[thrd:app]: Mock cluster enabled: original bootstrap.servers and security.protocol ignored and replaced with 127.0.0.1:55554,127.0.0.1:55556,127.0.0.1:55557
```

Attempt to manually create topic:

```cs
await adminClient.CreateTopicsAsync(new[] { new TopicSpecification { Name = "UnitTest" } });
```

fails with error

```log
Confluent.Kafka.KafkaException: Failed while waiting for controller: Local: Timed out

Confluent.Kafka.KafkaException
Failed while waiting for controller: Local: Timed out
   at Tests.ExampleUnitTestForConsumersAndOrProducers.SampleReproduction() in /Users/mac/github.com/rabotaua/kafka/Tests/ExampleUnitTestForConsumersAndOrProducers.cs:line 44
   at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_0.<<InvokeTestMethodAsync>b__1>d.MoveNext() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestInvoker.cs:line 264
--- End of stack trace from previous location ---
   at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in /_/src/xunit.execution/Sdk/Frameworks/ExecutionTimer.cs:line 48
   at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in /_/src/xunit.core/Sdk/ExceptionAggregator.cs:line 90



[thrd:app]: Mock cluster enabled: original bootstrap.servers and security.protocol ignored and replaced with 127.0.0.1:55662,127.0.0.1:55663,127.0.0.1:55664
```

Checklist
=========

Please provide the following information:
 - [x] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [x] Confluent.Kafka nuget version.
 - [x] Apache Kafka version.
 - [x] Client configuration.
 - [x] Operating system.
 - [x] Provide logs (with "debug" : "..." as necessary in configuration).
 - [x] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mac2000** [comment]
The same is true for newly released 2.1.1

**Comment by RFPAlves** [comment]
Use ProduceAsync instead.

```csharp
public class Example
{
    public async Task SampleReproduction()
    {

        var adminClient = new AdminClientBuilder(new ClientConfig(new Dictionary<string, string> { {"bootstrap.servers", "localhost:9200"}, {"test.mock.num.brokers", "3"} })).Build();
        var bootstrapServers = string.Join(",", adminClient.GetMetadata(TimeSpan.FromSeconds(1)).Brokers.Select(b => $"{b.Host}:{b.Port}"));

        var producer = new ProducerBuilder<Null, string>(new ProducerConfig { BootstrapServers = bootstrapServers }).Build();
        var consumer = new ConsumerBuilder<Ignore, string>(new ConsumerConfig { BootstrapServers = bootstrapServers, GroupId = "ExampleUnitTest", AutoOffsetReset = AutoOffsetReset.Earliest }).Build();
        var message = new Message<Null, string> { Value = "Test" };
        var topic = "UnitTest";

        await producer.ProduceAsync(topic, message);
        consumer.Subscribe(topic);

        var actual = consumer.Consume(TimeSpan.FromSeconds(10)).Message.Value;

        actual.Should().Be(message.Value);
    }
}
```

The broker has 0 topics initially, so the consumer has to wait for the topic to be created, as the Producer has the default AllowAutoCreateTopics property as true. I don't know why the previous versions of the library didn't have errors, it could be some change made in librdkafka 2.1.0.

**Comment by mac2000** [comment]
Thank you for clarification

Indeed seems like that's our case

We use sync version of `Produce` exactly because how it works internally and its fire and forget kind of nature

Changing it to `ProduceAsync` immediately solves broken test

Also we may prove your suggestion by just putting some small delay after producing our message, then everything will also work

So indeed there is something deep inside librdkafka changed and now sync produce method becomes even more fire and forget than before :)
