### ISSUE TITLE
Producer config doesn't accept "acks" or "request.required.acks"

### ISSUE THREAD

**Issue by bschmidtbauer** [confluentinc/confluent-kafka-dotnet#21]
I'm using Nuget package Confluent.Kafka v0.9.2-preview.

Config setup is essentially:
```
var config = new Dictionary<string, object>();
config.Add("bootstrap.servers", "[valid brokers here]");
config.Add("acks", 1);  // tried "all", 0, etc.
```

The exception that is thrown:
```
  System.InvalidOperationException was unhandled
  HResult=-2146233079
  Message=No such configuration property: "acks"
  Source=Confluent.Kafka
  StackTrace:
       at Confluent.Kafka.Impl.SafeConfigHandle.Set(String name, String value)
       at Confluent.Kafka.Producer.<>c__DisplayClass18_0.<.ctor>b__2(KeyValuePair`2 kvp)
       at System.Collections.Generic.List`1.ForEach(Action`1 action)
       at Confluent.Kafka.Producer..ctor(IEnumerable`1 config, Boolean manualPoll, Boolean disableDeliveryReports)
       at Confluent.Kafka.Producer`2..ctor(IEnumerable`1 config, ISerializer`1 keySerializer, ISerializer`1 valueSerializer, Boolean manualPoll, Boolean disableDeliveryReports)
       at Console.Producer.Program.Main(String[] args) in C:\Projects\tests\Kafka\ConfluentKafka\src\Console.Producer\Program.cs:line 19
  InnerException:
```

I have tried both "acks" and "request.required.acks" both have the same result.

Looking at the documentation and [code](https://github.com/edenhill/librdkafka/blob/master/src/rdkafka_conf.c) - it would appear this should work.

Am I doing something wrong?

**Comment by bschmidtbauer** [comment]
FWIW other producer specific config args do work (e.g. 'client.id', 'max.in.flight.requests.per.connection', 'retries', etc).

**Comment by edenhill** [comment]
`acks` is a topic-level configuration property, so you need to set it on the `default.topic.config` sub-dict of your configuration dict.
Here's an example (for the consumer, so it has other properties) that shows how to define the sub-dict:
https://github.com/confluentinc/confluent-kafka-dotnet/blob/e41f56cc7892da3382b29c1bca731456f5791d37/examples/AdvancedConsumer/Program.cs#L41

**Comment by bschmidtbauer** [comment]
Worked great - thanks!
