### ISSUE TITLE
Schema Registry Config SslCaLocation doesn't work

### ISSUE THREAD

**Issue by danielbojczuk** [confluentinc/confluent-kafka-dotnet#2140]
Description
===========
**Nuget Version**: Confluent.SchemaRegistry 2.3.0.
**Apache Kafka version**: Doesn't have influence
**Operating system**: Windows

SchemaRegistry Client is adding the CA certificates from the configuration SslCaLocation and SslKeystoreLocation to the HttpClientHandler.ClientCertificates Property:

- https://github.com/confluentinc/confluent-kafka-dotnet/blob/007a8ba83ce1c769b294e690309a48414a111944/src/Confluent.SchemaRegistry/CachedSchemaRegistryClient.cs#L298
- https://github.com/confluentinc/confluent-kafka-dotnet/blob/007a8ba83ce1c769b294e690309a48414a111944/src/Confluent.SchemaRegistry/Rest/RestService.cs#L89

But from the documentation, only the SSlKeystoreLocation should be placed on this HttpHandlers property for MTLS. The CA certificates should be handled differently: https://learn.microsoft.com/en-us/dotnet/api/system.net.http.httpclienthandler.clientcertificates?view=netcore-2.0

So, the current implementation doesn't allow you to connect to a schema registry server if it uses a certificate signed by a local CA. It throws the following exception:

```
Local: Key serialization error
 ---> System.Net.Http.HttpRequestException: [SERVER_URL] HttpRequestException: The SSL connection could not be established, see inner exception.
   at Confluent.SchemaRegistry.RestService.ExecuteOnOneInstanceAsync(Func`1 createRequest) in...
```

How to reproduce
================
Execute this code using a SchemaRegistry server using a locally signed SSL certificate:
```cs
var schemaConfig = new SchemaRegistryConfig
{
    Url = SCHEMA_REGISTRY_URL,
    SslKeystoreLocation = CERTIFICATE_PATH,
    SslKeystorePassword = CERTIFICATE_PASSWORD,
    SslCaLocation = TRUSTED_CA_FILEPATH,
};

var schemaregistry = new CachedSchemaRegistryClient(schemaConfig);
var keySerializer = new AvroSerializer<Application>(schemaregistry).AsSyncOverAsync();
var valueSerializer = new AvroSerializer<Event>(schemaregistry).AsSyncOverAsync();


var privKeyBytes = Convert.FromBase64String(PRIVATE_KEY_BASE64);
var privKeyPem = PemEncoding.Write("RSA PRIVATE KEY", privKeyBytes);

var producerConfig = new ProducerConfig
{
    BootstrapServers = BOOTSTRAP_SERVERS,

    SocketTimeoutMs = 30_000,
    ReconnectBackoffMaxMs = 10_000,

    SecurityProtocol = SecurityProtocol.Ssl,
    SslEndpointIdentificationAlgorithm = SslEndpointIdentificationAlgorithm.None,
    EnableSslCertificateVerification = true,
    SslCertificateLocation = PUBLIC_KEY_FILE_PATH,
    SslCaCertificateStores = "My",
    SslKeyPem = new string(privKeyPem),
};

var producer = new ProducerBuilder<Application, Event>(producerConfig)
    .SetKeySerializer(keySerializer)
    .SetValueSerializer(valueSerializer)
.Build();

var message = new Message<Application, Event>
{
    Key = EventHelper.CreateApplication(),
    Value = EventHelper.CreateEvent()
};

var result = await producer.ProduceAsync(TOPIC, message);

Console.WriteLine($"Written to offset {result.Offset.Value}");
```
The SchemaRegistry is hiding the InnerException, but with some debugging, you can check the real exception on  
https://github.com/confluentinc/confluent-kafka-dotnet/blob/007a8ba83ce1c769b294e690309a48414a111944/src/Confluent.SchemaRegistry/Rest/RestService.cs#L233
```
The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid because of errors in the certificate chain: UntrustedRoot
   at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions sslAuthenticationOptions)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Confluent.SchemaRegistry.RestService.ExecuteOnOneInstanceAsync(Func`1 createRequest) in
```

Workarounds
================
- Disable the SSL Certificate Checking using the EnableSslCertificateVerification=false, **which is not recommended at all**.

- If you add the same file used in TRUSTED_CA_FILEPATH to the **Trust Root Certificate Authorities** in Windows Certificate Stores, you can execute the code with success. **The problem is that in some cases (Azure Function Apps), you can't do this operation**
![image](https://github.com/confluentinc/confluent-kafka-dotnet/assets/39830414/742009f4-49f7-470f-9e47-498bd620e488)

Sugestion for solution
================
We could use the same approach as the Confluent.Kafka.ProducerConfig: being able to specify which certificate store you want to use:
https://github.com/confluentinc/confluent-kafka-dotnet/blob/007a8ba83ce1c769b294e690309a48414a111944/src/Confluent.Kafka/Config_gen.cs#L759

From .NET 5 and on, it is possible to add new Certificate Stores to the HttpClientHandler
https://github.com/dotnet/runtime/issues/39835#issuecomment-663020581

I would be happy to send a PR implementing the suggestion or another approach.

Checklist
=========

Please provide the following information:
 - [x] A complete (i.e., we can run it) minimal program demonstrating the problem. No need to supply a project file.
 - [x] Confluent.Kafka nuget version.
 - [x] Apache Kafka version.
 - [x] Client configuration.
 - [x] Operating system.
 - [x] Provide logs (with "debug" : "..." as necessary in configuration).
 - [x] Provide broker log excerpts.
 - [x] Critical issue.

**Comment by ahmar-husain** [comment]
I too face the same !

**Comment by DDiwakar369** [comment]
Hi Team, As the PR is merged when is this planned to release. Please let us know as we have the same issue and wanted to check if this already in the pipeline of release with in a few weeks

**Comment by sanderrhorst** [comment]
+1, we are also facing issues with this, especially when dotnet apps run in function apps in azure where we cannot import certificates into the Systems Truststore. Please fix this asap, really bad that it has still not been picked up because now the clients are lacking security and are vulnerable when setting up the connection to schema registry.

**Comment by andreycha** [comment]
2.8.0 still has this issue. According to release notes, the fix wasn't included there. Is there any information about when the fix will be released? Thank you!

**Comment by rayokota** [comment]
@andreycha the PR was merged, what error are you seeing?
