### ISSUE TITLE
TopicPartitionException

### ISSUE THREAD

**Issue by NZTSL** [confluentinc/confluent-kafka-dotnet#2162]
Description
===========

Hello,
I run some tests which call the Pause and Resume methods sequentially, it works well 90% of the time but they randomly fails with the following exception :

```
Confluent.Kafka.TopicPartitionException: An error occurred for topic partitions: [test-topic [[0]]].
    at Confluent.Kafka.Impl.SafeKafkaHandle.Resume(IEnumerable`1 partitions)
   at Confluent.Kafka.Consumer`2.Resume(IEnumerable`1 partitions)
```

Any idea of the reason ?
Thanks.

_Confluent.Kafka v2.3.0
Kafka v3.5-IV2
Debian Bullseye_

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [X] Confluent.Kafka nuget version.
 - [X] Apache Kafka version.
 - [ ] Client configuration.
 - [X] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by anchitj** [comment]
Can you provide the code where you face this issue? It's possible consumer group rebalances between Pause and Resume.

**Comment by DmitryParfonov** [comment]
Hello,
I'm getting the same exception when trying to Pause a consumer in the PartitionsAssignedHandler.
```csharp
new ConsumerBuilder<string, MyMessage>(consumerConfig)
.SetPartitionsAssignedHandler((consumer, topicPartitions) =>
{
    try
    {
        consumer.Pause(topicPartitions);
    }
    catch (TopicPartitionException ex)
    {
        Console.WriteLine("Error [{0}]: {1} |\n {2}", ex.Error.Code, ex.Error.Reason, ex.StackTrace);
        return;
    }

    Console.WriteLine("Consumer '{0}' Paused", 'myConsumer');
})
```

`TopicPartitionException` occurred:

**Kafka Error Code:** Local_Partial (-158):
**Message:** `An error occurred for topic partitions: [product-events [[0]], product-events [[1]], product-events [[2]], product-events [[3]], product-events [[4]]].

**StackTrace:**
```
at Confluent.Kafka.Impl.SafeKafkaHandle.Pause(IEnumerable`1 partitions)
   at Confluent.Kafka.Consumer`2.Pause(IEnumerable`1 partitions)
...
```
https://github.com/confluentinc/confluent-kafka-dotnet/blob/master/src/Confluent.Kafka/Impl/SafeKafkaHandle.cs#L1052

**Additional context:**
Generally speaking, I need to pause or resume a consumer under a special condition when a consumer group rebalance occurs.
