### ISSUE TITLE
JsonDeserializer thows ArgumentNullException when it is created.

### ISSUE THREAD

**Issue by marta-rostkowska** [confluentinc/confluent-kafka-dotnet#2235]
Description
===========
I want to use JsonDeserializer for kafka consumer but when it is initialized (new JsonDeserializer<Biometrics>(_schemaRegistryClient, schema, jsonSchemaGeneratorSettings: settings)) then exception with error: Value cannot be null. (Parameter 'key') is thrown:
```
   at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
   at System.Collections.Generic.Dictionary`2.ContainsKey(TKey key)
   at Confluent.SchemaRegistry.Serdes.JsonSchemaResolver.CreateSchemaDictUtil(Schema root)
   at Confluent.SchemaRegistry.Serdes.JsonSchemaResolver..ctor(ISchemaRegistryClient schemaRegistryClient, Schema schema, JsonSchemaGeneratorSettings jsonSchemaGeneratorSettings)
   at Confluent.SchemaRegistry.Serdes.JsonDeserializer`1..ctor(ISchemaRegistryClient schemaRegistryClient, Schema schema, IEnumerable`1 config, JsonSchemaGeneratorSettings jsonSchemaGeneratorSettings)
   at LiveDataClientsService.Kafka.Consumers.KafkaConsumerFactory.CreateConsumer[T](ISchemaRegistryClient schemaRegistryClient, Schema schema, Action`2 consumerErrorHandler) in C:\Users\rost9000\Projekty\multisport-fastpath-live-data-clients-service\LiveDataClientsService.Kafka\Consumers\KafkaConsumerFactory.cs:line 46
```
Error "Value cannot be null. (Parameter 'key')" is very enigmatic. Could somebody help me find out which key is missing?

How to reproduce
================

```
var settings = new JsonSchemaGeneratorSettings()
{
    SerializerSettings = new JsonSerializerSettings()
    {
        //TypeNameHandling = TypeNameHandling.All,
        Converters = new List<JsonConverter>
        {
            new Newtonsoft.Json.Converters.StringEnumConverter()
        },
        ContractResolver = new DefaultContractResolver
        {
            NamingStrategy = new CamelCaseNamingStrategy()
        },
    }
};

var topicName = "Biometrics";
var schemaName = $"{topicName}-value";

var producerConfig = _serviceProvider.GetRequiredService<IOptions<ProducerConfig>>();

var producer = new ProducerBuilder<string, Biometrics>(producerConfig.Value)
    .SetValueSerializer(serializer: new JsonSerializer<Biometrics>(_schemaRegistryClient, new JsonSerializerConfig()
    {
        AutoRegisterSchemas = true
    }, jsonSchemaGeneratorSettings: settings).AsSyncOverAsync())
    .Build();

await producer.ProduceAsync(topicName, new Message<string, Biometrics>()
{
    Key = "test",
    Value = message
});

var schema = await _schemaRegistryClient.GetLatestSchemaAsync(schemaName);

var config = new ConsumerConfig
{
    BootstrapServers = "localhost:29092",
    ClientId = "Test",
    GroupId = "Test",
    SecurityProtocol = SecurityProtocol.Plaintext,
    SaslMechanism = SaslMechanism.Plain,
    AutoOffsetReset = AutoOffsetReset.Earliest,
    EnableAutoCommit = true
};

var deserializer = new JsonDeserializer<Biometrics>(_schemaRegistryClient, schema, jsonSchemaGeneratorSettings: settings);

var consumer = new ConsumerBuilder<string, Biometrics>(config)
    .SetValueDeserializer(deserializer.AsSyncOverAsync())
    .Build();

public class Biometrics
{
    public Guid DeviceId { get; }
    public int MaxHeartRate { get; }

    public Biometrics(Guid deviceId, int maxHeartRate)
    {
        DeviceId = deviceId;
        MaxHeartRate = maxHeartRate;
    }
}
```
nuget versions:
* Apache.Avro Version=1.11.3
* Chr.Avro.Confluent Version=10.3.1
* Confluent.SchemaRegistry.Serdes.Avro Version=2.4.0
* JsonSubTypes Version=2.0.1
* Confluent.Kafka Version="2.4.0
* Confluent.SchemaRegistry Version=2.4.0
* Confluent.SchemaRegistry.Serdes.Json Version=2.4.0

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ ] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by nbo29** [comment]
I got a similar issue while producing events.
Stacktrace:
   at System.ThrowHelper.Throw(String paramName)
   at System.ThrowHelper.ThrowIfNull(Object argument, String paramName)
   at Microsoft.Extensions.Caching.Memory.MemoryCache.TryGetValue(Object key, Object& result)
   at Microsoft.Extensions.Caching.Memory.CacheExtensions.TryGetValue[TItem](IMemoryCache cache, Object key, TItem& value)
   at Confluent.SchemaRegistry.CachedSchemaRegistryClient.<GetLatestSchemaAsync>d__54.MoveNext()
   at Confluent.SchemaRegistry.AsyncSerde`1.<GetReaderSchema>d__20.MoveNext()
   at Confluent.SchemaRegistry.Serdes.JsonSerializer`1.<SerializeAsync>d__12.MoveNext()
   at Confluent.Kafka.Producer`2.<ProduceAsync>d__57.MoveNext()
