### ISSUE TITLE
 Failed to fetch committed offsets for partitions in

### ISSUE THREAD

**Issue by yeyijin** [confluentinc/confluent-kafka-dotnet#2240]
Description
===========
I use new topic and group. The topic has 10  partitions ， but no message.  The first consumer starts normally and is ready to consume as soon as there is news. 10 minutes later, the second consumer starts, but prompts 

Confluent.Kafka.ConsumeException: Failed to fetch committed offsets for partitions in group "my_group": Local: Broker transport failure
	  at Confluent.Kafka.Consumer`2.Consume(Int32 millisecondsTimeout)
	  at Confluent.Kafka.Consumer`2.Consume(CancellationToken cancellationToken)

Thanks.
How to reproduce
================

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ ] Confluent.Kafka nuget version.  Version=2.2.0.0

**Comment by yeyijin** [comment]
```c#
 var consumerConfig = new ConsumerConfig
 {
     BootstrapServers = host,
     AutoOffsetReset = AutoOffsetReset.Latest,//消费最新
     GroupId = group,
     EnableAutoOffsetStore = true,
     EnableAutoCommit = true,

 };

while (!stoppingToken.IsCancellationRequested)
{
    try
    {
        var msg = _consumer.Consume(stoppingToken);
   }
  catch (Exception ex)
  {
  }
}
```

**Comment by anchitj** [comment]
Can you provide debug logs?

**Comment by yeyijin** [comment]
> Can you provide debug logs?

hello. I have provided logs.What should be noted if two consumers from different topics are connected to two clusters
