### ISSUE TITLE
Small bug in Error.Reason getter?

### ISSUE THREAD

**Issue by comdw** [confluentinc/confluent-kafka-dotnet#397]
Description
===========
I think there is a small bug in Error.Reason when no reason has been set.  Null reference exception when mapping the error code to a string.

How to reproduce
================
Easy:
```
var error = new Error(ErrorCode.UnknownTopicOrPart);
Console.WriteLine(e.Reason);    <--- Throws

System.NullReferenceException: Object reference not set to an instance of an object.
   at Confluent.Kafka.Impl.LibRdKafka.err2str(ErrorCode err)
   at Confluent.Kafka.Error.ToString()
   at Confluent.Kafka.Error.get_Reason()
```

Checklist
=========
Please provide the following information:

 - [X] Confluent.Kafka nuget version: 0.11.3
 - [X] Apache Kafka version: 0.11.3

**Comment by mhowlett** [comment]
I think this is because the library isn't loaded (i.e. have you called `Library.Load` or instantiated a `Producer` or `Consumer`. Can you confirm? this behavior was actually by design, but in hindsight I'm going to label this a bug. I should auto-load librdkafka on any attempted usage of librdkafka functionality.

**Comment by comdw** [comment]
No this was in a unit test - I was just creating an example error response to test my calling class behaviour so that would make sense I guess.  Its easy to avoid by passing a reason into the constructor so I'm not too worried about this.

**Comment by mhowlett** [comment]
right. if you load librdkafka using `Library.Load` in your unit test, you shouldn't get the exception. I'll change the code to do this automatically.
