### ISSUE TITLE
Intermittent AggregateException exception on Producer Dispose

### ISSUE THREAD

**Issue by mhowlett** [confluentinc/confluent-kafka-dotnet#412]
Description
===========

I have seen the below exception thrown intermittently whilst running integration tests.

Failed   Confluent.Kafka.IntegrationTests.Tests.TypedProducer_ClosedHandle(bootstrapServers: "localhost:9092", topic: "test-topic-1", partitionedTopic: "test-topic-2")
Error Message:
 System.AggregateException : One or more errors occurred. (A task was canceled.)
---- System.Threading.Tasks.TaskCanceledException : A task was canceled.
Stack Trace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Confluent.Kafka.Producer.Dispose() in /git/confluent-kafka-dotnet/src/Confluent.Kafka/Producer.cs:line 688
   at Confluent.Kafka.Producer`2.Dispose() in /git/confluent-kafka-dotnet/src/Confluent.Kafka/Producer.cs:line 1325
   at Confluent.Kafka.IntegrationTests.Tests.TypedProducer_ClosedHandle(String bootstrapServers, String topic, String partitionedTopic) in /git/confluent-kafka-dotnet/test/Confluent.Kafka.IntegrationTests/Tests/ClosedHandle.cs:line 74
----- Inner Stack Trace -----

**Comment by mhowlett** [comment]
resolved by #413
