### ISSUE TITLE
Ocurrió un error: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. Parameter name: creationOptions

### ISSUE THREAD

**Issue by gacaq** [confluentinc/confluent-kafka-dotnet#427]
I have a project that should produce some messages in a kafka topic. When i run it local, the message is well produced. But when I plublish the project in a worker role I recieve that error message:

Ocurrió un error: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: creationOptions
   at System.Threading.Tasks.Task..ctor(Object state, TaskCreationOptions creationOptions, Boolean promiseStyle)
   at System.Threading.Tasks.TaskCompletionSource`1..ctor(Object state, TaskCreationOptions creationOptions)
   at Confluent.Kafka.SerializingProducer`2.Produce(String topic, TKey key, TValue val, Nullable`1 timestamp, Int32 partition, Boolean blockIfQueueFull)
   at Confluent.Kafka.SerializingProducer`2.ProduceAsync(String topic, TKey key, TValue val)
   at Satrack.Speeding.Infrastructure.Common.ProducerAdapter.<>n__0(String topic, Null key, String val)
   at Satrack.Speeding.Infrastructure.Common.ProducerAdapter.<Produce>d__1.MoveNext() in C:\Build Agents\default\_work\17\s\Speeding\Satrack.Speeding.Infrastructure\Common\ProducerAdapter.cs:line 18
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Satrack.Speeding.Data.Repositories.KafkaProducer.<ProduceMessage>d__3.MoveNext() in C:\Build Agents\default\_work\17\s\Speeding\Satrack.Speeding.Data\Repositories\KafkaProducer.cs:line 32
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Satrack.Speeding.Application.Services.KafkaQueueService.<SendMessageAsync>d__5.MoveNext() in C:\Build Agents\default\_work\17\s\Speeding\Satrack.Speeding.Application\Services\KafkaQueueService.cs:line 40
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Satrack.Speeding.Application.Services.EventsService.<EvaluateReportAsync>d__10.MoveNext() in C:\Build Agents\default\_work\17\s\Speeding\Satrack.Speeding.Application\Services\EventsService.cs:line 116
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Satrack.Speeding.Application.Services.EventsService.<ProcessEnqueuedReports>d__9.MoveNext() in C:\Build Agents\default\_work\17\s\Speeding\Satrack.Speeding.Application\Services\EventsService.cs:line 94
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Satrack.Speeding.Application.Services.EventsService.<ProcessReportAsync>d__8.MoveNext() in C:\Build Agents\default\_work\17\s\Speeding\Satrack.Speeding.Application\Services\EventsService.cs:line 69
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Satrack.Speeding.CloudApp.WorkerRole.Application.<Run>d__3.MoveNext() in C:\Build Agents\default\_work\17\s\Speeding\Satrack.Speeding.CloudApp.WorkerRole\Application.cs:line 37

The producer class code is as follows:

 public ProducerAdapter(IEnumerable<KeyValuePair<string, object>> config, ISerializer<Null> keySerializer, ISerializer<string> valueSerializer) : base(config, keySerializer, valueSerializer)
        {
        }

        public async Task Produce(string topic, Null key, string value)
        {
            --> await base.ProduceAsync(topic, key, value);
        }

        public virtual new void Dispose()
        {
            base.Dispose();
        }

The config for Kafka is:

private static Dictionary<string, object> ConstructConfig(string brokerList) =>
            new Dictionary<string, object>
            {
                { "bootstrap.servers", brokerList }
            };

The error trigger in in the next line in the producer:

 await base.ProduceAsync(topic, key, value);

Checklist
=========
Please provide the following information:

 - [x] Confluent.Kafka nuget version:
 - [ ] Apache Kafka version: 
 - [x] Client configuration:
 - [x] Operating system:
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [x] Critical issue

**Comment by mhowlett** [comment]
What is your target framework? What's going on isn't completely clear to me, but it looks like maybe `TaskCreationOptions.RunContinuationsAsynchronously` isn't supported in your environment for some reason. If you can upgrade to a newer .NET Framework, that will likely solve the issue if that's right.

https://github.com/confluentinc/confluent-kafka-dotnet/blob/master/src/Confluent.Kafka/Producer.cs#L885

**Comment by gacaq** [comment]
Actually my project run over .NET Framework 4.6.1

**Comment by mhowlett** [comment]
Can you try a synchronous call to `ProduceAsync` and see if that helps? (i.e. `ProduceAsync(topic, key, value).Result`). Also, I assume none of the calls to `ProduceAsync` are working? 

I wonder if this has anything to do with thread pool configuration (maybe you could look into that).

**Comment by gacaq** [comment]
Hi.

Mi initial version of the program I had a synchronous call of the method with .Wait() method. The message of the error was the same.

I read yesterday that .Result have the same behavior of .Wat method, isn't it?

**Comment by mhowlett** [comment]
yep, the same.

Are you running in Azure? please provide as much information as you can about your execution environment.

This seems likely a problem with the library and something we'll want to fix, so I'll label this a bug. If anyone else has run into this problem, please add to this thread. Unfortunately there are some higher priority tasks to get done before I'll get time to look further.

**Comment by gacaq** [comment]
Yes. I am running it in Azure. As a Multithreading small worker role

**Comment by mhowlett** [comment]
Are you able to get any program that uses Confluent.Kafka running in this environment? does even the simplest program fail?

**Comment by gacaq** [comment]
I have a Concluent.Kafka Consumer running in the same worker role. It's run correctly

**Comment by mhowlett** [comment]
what about a producer (using an async version of ProduceAsync)?

variants of  `ProduceAsync` that have an `IDeliveryHandler` parameter will avoid what I think the problem is and so I'm guessing they will work. At this stage i'd recommend trying to re-work your software to use one of those.

**Comment by gacaq** [comment]
Hi.

I tried with 

public void ProduceAsync(string topic, TKey key, TValue val, IDeliveryHandler<TKey, TValue> deliveryHandler);

And it works fine for me now.

Thanks for your advices :)

**Comment by mhowlett** [comment]
re-opening since this I believe there is a bug here we want to fix.

**Comment by gacaq** [comment]
Ok

**Comment by mhowlett** [comment]
the implementation of this has changed enormously on the 1.0 branch. because of this, and since this is an old issue which hasn't been reported again, closing.
