### ISSUE TITLE
about auto.offset.reset   config . 

### ISSUE THREAD

**Issue by liaodawee** [confluentinc/confluent-kafka-dotnet#428]
Description
===========
 when  i wrote a consumer config ..error occored...   i find this config from source-code
   private static Dictionary<string, object> constructConfig(string brokerList, bool enableAutoCommit, string reset = "lastest") =>
         new Dictionary<string, object>
         {
                             { "group.id", Guid.NewGuid() },
                             { "enable.auto.commit", enableAutoCommit },
                             { "auto.commit.interval.ms", 1000 },
                             { "session.timeout.ms",10000},
                            //{ "statistics.interval.ms", 60000 },
                             { "bootstrap.servers", brokerList },
                             //{ "default.topic.config", new Dictionary<string, object>()
                             //   {
                             //       { "auto.offset.reset", reset }
                             //   }
                             //}
                             { "auto.offset.reset",reset}

         };
**these two ways to set auto.offset.reset  are both failed..**

System.ArgumentException: Invalid value for configuration property "auto.offset.reset"
   at Confluent.Kafka.Impl.SafeConfigHandle.Set(String name, String value)
   at Confluent.Kafka.Consumer.<>c__DisplayClass11_0.<.ctor>b__3(KeyValuePair`2 kvp)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Confluent.Kafka.Consumer..ctor(IEnumerable`1 config)
   at Confluent.Kafka.Consumer`2..ctor(IEnumerable`1 config, IDeserializer`1 keyDeserializer, IDeserializer`1 valueDeserializer)

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] Confluent.Kafka nuget version:
 - [ ] Apache Kafka version: 
 - [ ] Client configuration:
 - [ ] Operating system:
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by liaodawee** [comment]
i resolve it ... cause i use old config
