### ISSUE TITLE
Crashes with debug turned on

### ISSUE THREAD

**Issue by TheMidgardWatcher** [confluentinc/confluent-kafka-dotnet#512]
Description
===========
When I'm trying to turn on debug, for instance with parameter ```debug=broker,protocol,topic,metadata,msg```
I'm getting such errors:
1)
```
FATAL: System.NullReferenceException: Object reference not set to an instance of an object.
EXCEPTION: Exception Type: System.NullReferenceException
Message: Object reference not set to an instance of an object.
HResult: -2147467261
Stack trace:[null]
```

2)
```
FATAL: System.IndexOutOfRangeException: Probable I/O race condition detected while copying memory. The I/O package is not thread safe by default. In multithreaded applications, a stream must be accessed in a thread-safe way, such as a thread-safe wrapper returned by TextReader's or TextWriter's Synchronized methods. This also applies to classes like StreamWriter and StreamReader.
   at System.Buffer.InternalBlockCopy(Array src, Int32 srcOffsetBytes, Array dst, Int32 dstOffsetBytes, Int32 byteCount)
   at System.IO.StreamWriter.Write(Char[] buffer, Int32 index, Int32 count)
   at System.IO.TextWriter.SyncTextWriter.WriteLine(String value)
   at Confluent.Kafka.Loggers.ConsoleLogger(Object obj, LogMessage logInfo)
EXCEPTION: Exception Type: System.IndexOutOfRangeException
Message: Probable I/O race condition detected while copying memory. The I/O package is not thread safe by default. In multithreaded applications, a stream must be accessed in a thread-safe way, such as a thread-safe wrapper returned by TextReader's or TextWriter's Synchronized methods. This also applies to classes like StreamWriter and StreamReader.
Source: mscorlib
HResult: -2146233080
Stack trace:
       at System.Buffer.InternalBlockCopy(Array src, Int32 srcOffsetBytes, Array dst, Int32 dstOffsetBytes, Int32 byteCount)
       at System.IO.StreamWriter.Write(Char[] buffer, Int32 index, Int32 count)
       at System.IO.TextWriter.SyncTextWriter.WriteLine(String value)
       at Confluent.Kafka.Loggers.ConsoleLogger(Object obj, LogMessage logInfo)
```

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] Confluent.Kafka nuget version:
 - [ ] Apache Kafka version: 
 - [ ] Client configuration:
 - [ ] Operating system:
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [x] Critical issue

**Comment by mhowlett** [comment]
@TheMidgardWatcher can you try overwriting the default log handler using following:

```
                object lockObj = new object();
                producer.OnLog += (_, logInfo) => 
                { 
                    lock (lockObj) 
                    {
                        var now = DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss.fff");
                        Console.Error.WriteLine($"{logInfo.Level}|{now}|{logInfo.Name}|{logInfo.Facility}| {logInfo.Message}");
                    }
                };
```

it seems as though `Console.Error.WriteLine` calls need to be synchronized and we're not doing that. Please let me know if this works!

**Comment by TheMidgardWatcher** [comment]
Hi Matt,

I've just tried it and got the same error:
```
2018-04-20 09:38:43.4951 - FATAL: System.IndexOutOfRangeException: Probable I/O race condition detected while copying memory. The I/O package is not thread safe by default. In multithreaded applications, a stream must be accessed in a thread-safe way, such as a thread-safe wrapper returned by TextReader's or TextWriter's Synchronized methods. This also applies to classes like StreamWriter and StreamReader.
   at System.Buffer.InternalBlockCopy(Array src, Int32 srcOffsetBytes, Array dst, Int32 dstOffsetBytes, Int32 byteCount)
   at System.IO.StreamWriter.Write(Char[] buffer, Int32 index, Int32 count)
   at System.IO.TextWriter.SyncTextWriter.WriteLine(String value)
   at Confluent.Kafka.Loggers.ConsoleLogger(Object obj, LogMessage logInfo)
```

There is only one difference with your code snippet - I'm using NLog logger inside of OnLog event handler.

PS: And I caught it in consumer this time, not in the producer.

**Comment by mhowlett** [comment]
I'm unsure why the stack trace includes `ConsoleLogger` if you're replaced the log handler with something else.

Labelled this as a bug since I need to update `ConsoleLogger` to include synchronization noted above.

**Comment by mhowlett** [comment]
just added synchronization to the `Producer` and `Consumer` log handlers on the 1.0-experimental branch.
