### ISSUE TITLE
System.AccessViolationException when QueryWatermarkOffsets times out after Consumer is closed

### ISSUE THREAD

**Issue by LucVL** [confluentinc/confluent-kafka-dotnet#622]
Description
===========
I ran into the following exception:
```
Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Confluent.Kafka.Impl.NativeMethods.NativeMethods.rd_kafka_query_watermark_offsets(IntPtr rk, String topic, Int32 partition, Int64& low, Int64& high, IntPtr timeout_ms)
   at Confluent.Kafka.Impl.LibRdKafka.query_watermark_offsets(IntPtr rk, String topic, Int32 partition, Int64& low, Int64& high, IntPtr timeout_ms)
   at Confluent.Kafka.Impl.SafeKafkaHandle.QueryWatermarkOffsets(String topic, Int32 partition, Int32 millisecondsTimeout)
   at Confluent.Kafka.Consumer.QueryWatermarkOffsets(TopicPartition topicPartition, TimeSpan timeout)
... etc
```

It turned out I hadn't created a certain topic causing both QueryWatermarkOffsets and Consume to time out on two different threads and the consumer being closed before the QueryWatermarkOffsets thread timed out.

How to reproduce
================

I managed to reduce the offending code to the following snippet that consistently reproduces the exception:
```
using System;
using System.Collections.Generic;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using Confluent.Kafka;
using Confluent.Kafka.Serialization;

namespace TopicReader
{
    class Program
    {
        static void Main(string[] args)
        {
            var config = new Dictionary<string, object>
            {
                ["bootstrap.servers"] = "...:9092",
                ["group.id"] = nameof(TopicReader),
            };

            using (var consumer = new Consumer<string, string>(config, new StringDeserializer(Encoding.UTF8), new StringDeserializer(Encoding.UTF8)))
            {
                var topicPartition = new TopicPartition("xxx-yyy", 0); // Use  a non-existent topic here!

                Task.Run(() =>
                {
                    var watermarkOffsets = consumer.QueryWatermarkOffsets(topicPartition, TimeSpan.FromSeconds(2));

                    Console.WriteLine("consumer.QueryWatermarkOffsets = " + watermarkOffsets);
                });

                Thread.Sleep(TimeSpan.FromSeconds(1));
            }

            Thread.Sleep(TimeSpan.FromSeconds(3));
        }
    }
}
```

There must be some race condition because tweaking the timings (e.g. commenting out the first Thread.Sleep) causes the program to pass...

I post the problem here, but I think the issue should be fixed in the underlying librdkafka library since it's an exception that should not occur in C#

I know that the consumer should not be closed before all other threads are done using it, but even so librdkafka should throw a proper exception and not do an invalid memory access.

Checklist
=========
Please provide the following information:

 - [v] Confluent.Kafka nuget version: v0.11.5
 - [v] librdkafka.redist version: v0.11.5
 - [v] Apache Kafka version: kafka_2.11-1.0.2
 - [ ] Client configuration: 
 - [v] Operating system: Windows 10
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
Thanks for reporting @LucVL (and sorry for the delay in replying). As you point out, what's happening is either your code is managing to call `QueryWatermarkOffsets` just after the client is disposed (in which case the problem is fixed in 1.0-experimental), or the client is getting disposed during the call to QueryWatermarkOffsets - neither are supported operations. We could prevent an access violation exception in the latter case by blocking the consumer dispose (not good!) until all method calls are complete, or changing the librdkafka query watermark offsets call to be async (queue based). Both would require additional tracking logic. Markgin this a low priority enhancement.

**Comment by Caskia** [comment]
Beta 1.0.0 has the same problem!

**Comment by mohamed-firoz** [comment]
no fixes for this ?
