### ISSUE TITLE
Issue Consuming Data

### ISSUE THREAD

**Issue by bryanjeffrey** [confluentinc/confluent-kafka-dotnet#69]
Hello.

I was working to move over from RdKafkaNet (https://github.com/ah-/rdkafka-dotnet). I converted our codebase over to using the confluent library. I am seeing a couple of issues:

1.  With Kafka 0.8.2.1 consuming data I see the following error:

5|2017-02-21 09:25:22.482|rdkafka#consumer-1|FAIL| localhost:9092/12: Connection closed

The Kafka console consumer is working against the same Kafka server/Zookeeper (a single node local instance I am using for test), so that would not seem to be the issue. On the Kafka Server side I am seeing the following errors:

[2017-02-21 09:36:34,509] ERROR Closing socket for /127.0.0.1 because of error (kafka.network.Processor)
org.apache.kafka.common.protocol.types.SchemaException: Error reading field 'topics': java.nio.BufferUnderflowException
at org.apache.kafka.common.protocol.types.Schema.read(Schema.java:66)
at org.apache.kafka.common.requests.JoinGroupRequest.parse(JoinGroupRequest.java:85)
at kafka.api.JoinGroupRequestAndHeader$.readFrom(JoinGroupRequestAndHeader.scala:29)
at kafka.api.RequestKeys$$anonfun$12.apply(RequestKeys.scala:50)
at kafka.api.RequestKeys$$anonfun$12.apply(RequestKeys.scala:50)
at kafka.network.RequestChannel$Request.(RequestChannel.scala:50)
at kafka.network.Processor.read(SocketServer.scala:450)
at kafka.network.Processor.run(SocketServer.scala:340)
at java.lang.Thread.run(Thread.java:745)

This error is resolved moving to Kafka 0.9.0.1

2. Unable to consume data

While I'm no longer seeing an error after the Kafka version change, I am not seeing consumed messages. I've worked all the way back from my code back to the example code for both poll and consume advanced consumer (https://github.com/confluentinc/confluent-kafka-dotnet/blob/master/examples/AdvancedConsumer/Program.cs). Neither of these samples appear to work out of the box. 

The older RdKafka code (https://github.com/ah-/rdkafka-dotnet) continues to work, and I also see the Kafka console consumer/producer produce/consume data. I've tried the following:

Turned on exception processing - no exceptions to note.
Verified connection to the broker from broker logs & validated exception when broker is terminated
Double checked correct topic specification
Do you have any thoughts on how I could further debug this issue?

**Comment by edenhill** [comment]
For older broker versions you need to tell the client what broker version it is connecting to.
See here for more information:
https://github.com/edenhill/librdkafka/wiki/Broker-version-compatibility
