### ISSUE TITLE
Schema Registry URL with URL path does not work

### ISSUE THREAD

**Issue by WSt89** [confluentinc/confluent-kafka-dotnet#934]
Description
===========
I am using confluent-kafka-dotnet library (Nuget Confluent.Kafka.Avro 0.11.6) for consuming Avro messages. We moved our infrastructure (Kafka broker (Image:confluentinc/cp-enterprise-kafka:5.0.0) , Schema Registry (confluentinc/cp-schema-registry:5.0.0), etc) to a Kubernetes cluster (Kubelet Version v1.10.6) where the schema-registry is behind an ingress now. 
Therefore, when I want to test consuming Avro messages from the outside of the cluster (my Windows 10 machine), i need to set the schema-registry's ingress url on consumer side ( something like that: hostname:80/schema-registry/). However, it seems like that the library can't handle schema-registry URLs with URL paths well (it seems to request a different URL somehow and therefore it receives some HTML from the Kubernetes ingress handler instead of the expected Avro schema.). 
However, calling the configured URL manually exposes the schema registries API as expected and using the Schema registry with an exposed Kubernetes-Node port works (e.g., hostname:30002)

Error message:

`2019-05-13 15:14:31.9572 ERROR Job:  () Microsoft.Extensions.Logging.ILogger Message:OnConsumeError: System.AggregateException: One or more errors occurred. (Unexpected character encountered while parsing value: <. Path '', line 0, position 0.) ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at Confluent.SchemaRegistry.RestService.ExecuteOnOneInstanceAsync(HttpRequestMessage request)
   at Confluent.SchemaRegistry.RestService.RequestAsync[T](String endPoint, HttpMethod method, Object[] jsonBody)
   at Confluent.SchemaRegistry.RestService.GetSchemaAsync(Int32 id)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Confluent.SchemaRegistry.CachedSchemaRegistryClient.GetSchemaAsync(Int32 id)
   at Confluent.Kafka.Serialization.SpecificDeserializerImpl`1.Deserialize(String topic, Byte[] array)
   at Confluent.Kafka.Serialization.MessageExtensions.Deserialize[TKey,TValue](Message message, IDeserializer`1 keyDeserializer, IDeserializer`1 valueDeserializer)
---> (Inner Exception #0) Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at Confluent.SchemaRegistry.RestService.ExecuteOnOneInstanceAsync(HttpRequestMessage request)
   at Confluent.SchemaRegistry.RestService.RequestAsync[T](String endPoint, HttpMethod method, Object[] jsonBody)
   at Confluent.SchemaRegistry.RestService.GetSchemaAsync(Int32 id)<---`

How to reproduce
================

Schema registry url contains ingress path like "hostname:80/schema-registry/"

**Comment by mhowlett** [comment]
see #677

**Comment by mhowlett** [comment]
I believe this should be resolved in 1.3.0-PRE1. If the problem persists, please update in #677.
