### ISSUE TITLE
AvroSerializer/SchemaRegistry works on .NET Core but not .NET Framework 4.5.2

### ISSUE THREAD

**Issue by xiaojie2019** [confluentinc/confluent-kafka-dotnet#955]
Description
===========
I have following the sample code (https://github.com/confluentinc/confluent-kafka-dotnet/tree/master/examples/AvroSpecific) to build a Kafka Avro Producer with C# code. But it works perfectly on .NET Core project, but failed on .NET Framework 4.5.2. Failed reason is key and value serialization error.

How to reproduce
================
Build and Run the code provided below on Visual Studio 2015 Target Framework 4.5.2

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.

public class Program
    {
        public static void Main(string[] args)
        {
            try {
                string bootstrapServer = "myBootstrapServer";
                string topicName = "myTopicName";
                string schemaRegistryUrl = "myUrl";
                var saslUsername = "username";
                var saslPassword="password";
				var sslCaLocation = "sslCaLocation"

                var config = new ProducerConfig
                {
                    BootstrapServers = bootstrapServer,
                    SecurityProtocol = SecurityProtocol.SaslSsl,
                    SaslMechanism = SaslMechanism.ScramSha512,
                    SaslUsername = saslUsername,
                    SaslPassword = saslPassword,
                    SslCaLocation = sslCaLocation,
                };

                var schemaRegistryConfig = new SchemaRegistryConfig
                {
                    SchemaRegistryUrl = schemaRegistryUrl,
                    SchemaRegistryBasicAuthCredentialsSource = AuthCredentialsSource.UserInfo,
                    SchemaRegistryBasicAuthUserInfo = saslUsername + ":" + saslPassword,
                    SchemaRegistryRequestTimeoutMs = 5000,
                    SchemaRegistryMaxCachedSchemas = 10
                };

                using (var schemaRegistry = new CachedSchemaRegistryClient(schemaRegistryConfig))
                using (var producer =
                        new ProducerBuilder<string, RepublishRequest>(config)
                            .SetKeySerializer(new AvroSerializer<string>(schemaRegistry))
                            .SetValueSerializer(new AvroSerializer<RepublishRequest>(schemaRegistry))
                            .Build())
                {
                    RepublishRequest request = new RepublishRequest { EntityType = EntityType.RMSSKU,
                        EntityId = "53486682",
                        Market = Market.US,
                        SellingChannel = SellingChannel.RACK,
                        ApplicationId = "TestApp"
                    };

                    byte[] val = SerializerAvro.Serialize(request);
                    var task = producer.ProduceAsync(topicName, new Message<string, RepublishRequest> { Key = "test", Value = request });
                    task.Wait();

                    if (task.IsFaulted) {
                        Console.Write($"error producing message: {task.Exception.Message}");
                    } else {
                        Console.Write($"produced to: {task.Result.TopicPartitionOffset}");
                    }
                    producer.Flush(TimeSpan.FromSeconds(10));
                }
            } catch (Exception e) {
                Console.Write($"EXCEPTION: {e}");
            }
        }

    }

RepublishRequest is auto generated Avro class.

 - [ ] Confluent.Kafka nuget version.
1.0.0

 - [ ] Apache Kafka version.
 - [ ] Client configuration.

 - [ ] Operating system.
Windows 10

 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).

 - [ ] Provide broker log excerpts.

EXCEPTION: System.AggregateException: One or more errors occurred. ---> Confluent.Kafka.ProduceException`2[System.String,com.nordstrom.rms.republish.RepublishRequest]: Local: Key serialization error ---> System.Net.Http.HttpRequestException: [https://schema-registry.nonprod.us-west-2.aws.proton.nordstrom.com/] HttpRequestException: An error occurred while sending the request.
   at Confluent.SchemaRegistry.RestService.<ExecuteOnOneInstanceAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Confluent.SchemaRegistry.RestService.<RequestAsync>d__6`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Confluent.SchemaRegistry.RestService.<RegisterSchemaAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Confluent.SchemaRegistry.CachedSchemaRegistryClient.<RegisterSchemaAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Confluent.SchemaRegistry.Serdes.SpecificSerializerImpl`1.<Serialize>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Confluent.SchemaRegistry.Serdes.AvroSerializer`1.<SerializeAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Confluent.Kafka.Producer`2.<ProduceAsync>d__51.MoveNext()
   --- End of inner exception stack trace ---
   at Confluent.Kafka.Producer`2.<ProduceAsync>d__51.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Confluent.Kafka.Examples.SimpleProducer.Program.Main(String[] args) in C:\MyWork\TestApplication\SimpleKafkaProducer\Program.cs:line 79
---> (Inner Exception #0) Confluent.Kafka.ProduceException`2[System.String,com.nordstrom.rms.republish.RepublishRequest]: Local: Key serialization error ---> System.Net.Http.HttpRequestException: [https://schema-registry.nonprod.us-west-2.aws.proton.nordstrom.com/] HttpRequestException: An error occurred while sending the request.
   at Confluent.SchemaRegistry.RestService.<ExecuteOnOneInstanceAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Confluent.SchemaRegistry.RestService.<RequestAsync>d__6`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Confluent.SchemaRegistry.RestService.<RegisterSchemaAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Confluent.SchemaRegistry.CachedSchemaRegistryClient.<RegisterSchemaAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Confluent.SchemaRegistry.Serdes.SpecificSerializerImpl`1.<Serialize>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Confluent.SchemaRegistry.Serdes.AvroSerializer`1.<SerializeAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Confluent.Kafka.Producer`2.<ProduceAsync>d__51.MoveNext()
   --- End of inner exception stack trace ---
   at Confluent.Kafka.Producer`2.<ProduceAsync>d__51.MoveNext()<---
Enter to exit

 - [ ] Critical issue.

**Comment by aquiros-modus** [comment]
Any update related to this issue? Same case for me. Visual Studio 2015 Target Framework 4.5.2

**Comment by Anhbta** [comment]
Same issue with .net core 3.x

**Comment by magician123** [comment]
I am facing the same error  with .net 4.6.1

**Comment by mhowlett** [comment]
the stack trace above, the inner exception is `System.Net.Http.HttpRequestException`, which indicates the serializer had trouble communicating with schema registry. 

@magician123 , @Anhbta , @aquiros-modus - do you also see `HttpRequestException`, or is the underlying problem something else? I can't think of a reason this would occur in .net framework but not .net core - the execution paths are not different. it seems like at the very least there is a common trap here somewhere though.

**Comment by AlfaIrawan** [comment]
@mhowlett I also have problem with .net core 2.1

Here's my code

> [HttpPost("storeType")]
        [ProducesResponseType(typeof(HttpResponseBodySingle<StoreTypeResponse>), 200)]
        public async Task<IActionResult> Create([FromBody]AddStoreTypeRequest model)
        {
            
            string apiVersion = "****";
            string organization = "****";
            
            Error errors;
            
            if(model == null)
            {
                errors = new Error
                {
                    error_code = "2",
                    error_message = "Data invalid"
                };
                
                HttpResults = new HttpResponseBodySingle<string>(apiVersion, organization, Web.System.Enumerations.StatusCode.Ok,StatusMessage.Success, errors, null);
                return HttpResponse(HttpResults);
            }

            try
            {
                StoreTypeResponse data = IUnitOfWorks.UnitOfWorkStoreType().AddStoreType(model);
                
                var config = new ProducerConfig { BootstrapServers = "localhost:9092" };
                var schemaRegistryConfig = new SchemaRegistryConfig { Url = "localhost:8081" };
                var avroSerializerConfig = new AvroSerializerConfig { BufferBytes = 100 };
                
                _messageHubContexts.Clients.All.SendAsync("AddStoreType",data);
                HttpResults = new HttpResponseBodySingle<StoreTypeResponse>(apiVersion, organization, Web.System.Enumerations.StatusCode.Ok, StatusMessage.Success, null, data);
                
                using (var schemaRegistry = new CachedSchemaRegistryClient(schemaRegistryConfig))
                using (var p = new ProducerBuilder<string, StoreTypeSchemaRegistry>(config)
                    .SetKeySerializer(new AvroSerializer<string>(schemaRegistry,avroSerializerConfig))
                    .SetValueSerializer(new AvroSerializer<StoreTypeSchemaRegistry>(schemaRegistry,avroSerializerConfig))
                    .Build())
                {
                    StoreTypeSchemaRegistry storeTypeSchemaRegistry = new StoreTypeSchemaRegistry { storeTypeId = data.storeTypeId, code = data.code, name = data.name, createdBy = data.createdBy, createdDate = data.createdDate.ToString(), createdFrom = data.createdFrom, modifiedBy = data.modifiedBy, modifiedDate = data.modifiedDate.ToString(), modifiedFrom = data.modifiedFrom};
                    var dr = await p
                        .ProduceAsync("storetype", new Message<string, StoreTypeSchemaRegistry> { Key = data.storeTypeId, Value=storeTypeSchemaRegistry });
                }
            }
            catch(Exception ex)
            {
                switch (ex.Message)
                {
                    case "1":
                        errors = new Error
                        {
                            error_code = "1",
                            error_message = "Data not found"
                        };
                        break;
                    case "2":
                        errors = new Error
                        {
                            error_code = "2",
                            error_message = "Data invalid"
                        };
                        break;
                    case "3":
                        errors = new Error
                        {
                            error_code = "3",
                            error_message = "Duplicate data"
                        };
                        break;
                    case "4":
                        errors = new Error
                        {
                            error_code = "4",
                            error_message = "Value cannot be null"
                        };
                        break;
                    default:
                        errors = new Error
                        {
                            error_code = ex.HResult.ToString(),
                            error_message = ex.Message
                        };
                        break;
                }

                HttpResults = new HttpResponseBodySingle<string>(apiVersion, organization, Web.System.Enumerations.StatusCode.Ok,StatusMessage.Success, errors, null);
            }

            return HttpResponse(HttpResults);

        }

**Comment by magician123** [comment]
@confluentinc it was actually the certs that had issues in my case, its now resolved. Thanks.

**Comment by Ealenn** [comment]
The `serialization error` was throw when credentials or registry configuration was incorrect.

**Comment by mhowlett** [comment]
marking as enhancement since I think we probably want to surface a different top level exception (that derives from ProduceException) for various common problems with SR integration.

**Comment by bishal1990** [comment]
Local: Key serialization error issue please help

**Comment by WhiskyLiu** [comment]
Hello.
Any update related to this issue? Same case for me. Visual Studio 2017 Target Framework 4.6.1.
Please help...

**Comment by vishwajeets7** [comment]
@mhowlett 
Do you have any updates to share? or any work around on this issue. Looks like common for .net platform. 
Earliest resolution would be appreciated.

Thanks in advance.

**Comment by jake0029** [comment]
@mhowlett do we have any updates on this?

**Comment by saloni-patil-maersk** [comment]
@timarape  : Were you able to make it work with .net 4.6.1 or did you upgrade?

**Comment by saloniapatil** [comment]
@timarape : Were you able to make it work with .net 4.6.1 or did you upgrade?
