### ISSUE TITLE
Confluent. Kafka System Null Exception encountered

### ISSUE THREAD

**Issue by jake0029** [confluentinc/confluent-kafka-dotnet#962]
Exception: System.NullReferenceException

Message: Object reference not set to an instance of an object.

StackTrace:   at Confluent.Kafka.Impl.NativeMethods.NativeMethods.rd_kafka_destroy(IntPtr rk)
  at Confluent.Kafka.Impl.SafeKafaHandle.ReleaseHandle()
  at System.Runtime.InteropServices.SafeHandle.InternalFinalize()
  at System.Runtime.InteropServices.SafeHandle.Finalize();

I always encounter this error everytime i deployed my app (release version) , using a cross consumer-producer-consumer pattern in my program, seeking assistance on this issue please since application is not responding

**Comment by jake0029** [comment]
confluent.kafka version is 0.11.5

**Comment by mhowlett** [comment]
suggest upgrading to 1.0 which includes a number of fixes related to object dispose / finalization.

**Comment by jake0029** [comment]
Hello @mhowlett,

 Already upgraded librdkafka to version 1.0, now my was not able to seek partition and offset with error [Local: Errorneous state] and also encounters [rdkafka|producer-2|CONFWARN| thrd app: Configuration property produce.offset.report is deprecated: No longer used], 

Please advised. Thanks

**Comment by anchitj** [comment]
Is this still an issue?
